REM   Script: MWD Schema
REM   STAGE 4 todo: DML FOR PERSON: DEFAULT)
	
insert into PERSONS (PERSON_ID, EMAIL, PHONE_FIXED, IS_COMPETITOR, PERSON_TYPE) 
	VALUES (1,'GERDIENBOOM@HOTMAIL.COM','0031546572511','N','LEGAL_PERSON');
insert into LEGAL_PERSONS (PERSON_ID, LEGAL_NAME, WEBSITE) 
	VALUES ((SELECT PERSON_ID FROM PERSONS WHERE EMAIL = 'GERDIENBOOM@HOTMAIL.COM' AND PERSON_TYPE = 'LEGAL_PERSON'),'PLEISTERPLAATS DE BARKEL','WWW.PLEISTERPLAATSDEBARKEL.NL');
insert into LOCATIONS (LOCATION_ID, PERSON_ID)
	VALUES (1, (SELECT PERSON_ID FROM PERSONS WHERE EMAIL = 'GERDIENBOOM@HOTMAIL.COM' AND PERSON_TYPE = 'LEGAL_PERSON'));
insert into LOCATION_ADDRESSES (LOCATION_ADDRESS_ID, LOCATION_ID, STREET, NR, NR_ADDITION, CITY, COUNTRY, POSTAL_CODE, IS_MAIN, IS_ACTIVE, ADDRESS_TYPE)
	VALUES ((SELECT LOCATION_ID FROM LOCATIONS WHERE PERSON_ID = (SELECT PERSON_ID FROM PERSONS WHERE EMAIL = 'GERDIENBOOM@HOTMAIL.COM' AND PERSON_TYPE = 'LEGAL_PERSON')), (SELECT PERSON_ID FROM PERSONS WHERE EMAIL = 'GERDIENBOOM@HOTMAIL.COM' AND PERSON_TYPE = 'LEGAL_PERSON'), 'HEXELSEWEG', 52, 'B', 'WIERDEN', 'THE NETHERLANDS', '7641 PR','Y','Y','ESTABLISHMENT');

insert into PERSONS (PERSON_ID, EMAIL, PHONE_FIXED, IS_COMPETITOR, PERSON_TYPE) 
	VALUES (2,'ANONYMOUS', 'ANONYMOUS', 'N','NATURAL_PERSON');
insert into NATURAL_PERSONS (PERSON_ID, FIRST_NAME, LAST_NAME)
	VALUES ((SELECT PERSON_ID FROM PERSONS WHERE EMAIL = 'ANONYMOUS' AND PERSON_TYPE = 'NATURAL_PERSON'),'ANONYMOUS','ANONYMOUS');
insert into LOCATIONS (LOCATION_ID, PERSON_ID)
	VALUES (2, (SELECT PERSON_ID FROM PERSONS WHERE EMAIL = 'ANONYMOUS' AND PERSON_TYPE = 'NATURAL_PERSON'));
insert into LOCATION_ADDRESSES (LOCATION_ADDRESS_ID, LOCATION_ID, STREET, CITY, COUNTRY, IS_MAIN, IS_ACTIVE, ADDRESS_TYPE)
	VALUES ((SELECT LOCATION_ID FROM LOCATIONS WHERE PERSON_ID = (SELECT PERSON_ID FROM PERSONS WHERE EMAIL = 'ANONYMOUS' AND PERSON_TYPE = 'NATURAL_PERSON')), (SELECT PERSON_ID FROM PERSONS WHERE EMAIL = 'ANONYMOUS' AND PERSON_TYPE = 'NATURAL_PERSON'), 'ANONYMOUS_STREET', 'ANONYMOUS_TOWN', 'ANONYMOUS_COUNTRY','Y','Y', 'OTHER');



