SET DEFINE OFF

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('NATURAL', 'NATURAL', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('COLOR MIX', 'COLOR MIX', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('RAINBOW', 'RAINBOW', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('RED', 'RED', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('PURPLE', 'PURPLE', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('GREEN', 'GREEN', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('ORANGE', 'ORANGE', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('PINK', 'PINK', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('YELLOW', 'YELLOW', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('BLUE', 'BLUE', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('BROWN', 'BROWN', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('BLACK', 'BLACK', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('SILVER', 'SILVER', 'NORMAL', 'SHINY', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('BEIGE', 'BEIGE', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('BLACKENED STAINLESS', 'STAINLESS STEEL', 'NORMAL', 'MATTE', 'BLACKENED');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('COFFEE BROWN', 'BROWN', 'NORMAL', 'MATTE', 'COFFEE');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('DEEP RED', 'RED', 'DARK', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('BLACK SILVER', 'SILVER', 'NORMAL', 'MATTE', 'BLACK');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('DARK COFFEE BROWN', 'BROWN', 'DARK', 'MATTE', 'COFFEE');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('DARK GREEN', 'GREEN', 'DARK', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('DARK STEEL BLUE', 'STEEL', 'DARK', 'MATTE', 'BLUE');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('PURPLE RED', 'RED', 'NORMAL', 'MATTE', 'PURPLE');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('TURQUOISE', 'TURQUOISE', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('LIGHT BROWN', 'BROWN', 'LIGHT', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('SHINY RED', 'RED', 'NORMAL', 'SHINY', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('SHINY STEEL', 'STEEL', 'NORMAL', 'SHINY', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('SHINY PURPLE', 'PURPLE', 'NORMAL', 'SHINY', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('GOLD', 'GOLD', 'NORMAL', 'SHINY', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('SHINY ORANGE', 'ORANGE', 'NORMAL', 'SHINY', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('SHINY GREEN', 'GREEN', 'NORMAL', 'SHINY', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('SHINY LIGHT BLUE', 'BLUE', 'LIGHT', 'SHINY', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('SHINY BLUE', 'BLUE', 'NORMAL', 'SHINY', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('NEW BRONZE', 'BRONZE', 'NORMAL', 'SHINY', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('ANTIQUE BRONZE', 'BRONZE', 'NORMAL', 'MATTE', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('BRASS', 'BRASS', 'NORMAL', 'SHINY', 'NULL');

INSERT INTO COLORS (NAME, BASE_COLOR, TINT, COLOR_TYPE, ADDED_COLOR) 
VALUES ('COPPER', 'COPPER', 'NORMAL', 'SHINY', 'NULL');

-- Import Data into table COLORS from file J:\CarinaOneDrive\OneDrive\Documents\Boom Projects\MetalWeaves\db\mwd_git\SourceFiles\colorForWorkbench.csv . Task successful and sent to worksheet.