
SET DEFINE OFF

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('OTH', 'OTHER', 'NULL', 'NULL', 'NULL', 'UNKNOWN', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('OTH-MET', 'OTHER METAL', 'NULL', 'NULL', 'NULL', 'NULL', 'OTH');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('SST', 'STAINLESS STEEL', 'NULL', 'NULL', 'NULL', 'UNKNOWN', 'ST');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('SST-BL', 'STAINLESS STEEL', 'BLACKENED', 'NULL', 'NULL', 'NULL', 'SST');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('PL-SST', 'STAINLESS STEEL', 'PLATED', 'OTHER', 'NULL', 'NULL', 'SST');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('PL-SST-TI', 'STAINLESS STEEL', 'PLATED', 'TITANIUM', 'NULL', 'TITANIUM', 'SST');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('BA', 'BASE ALUMINIUM', 'NULL', 'NULL', 'NULL', 'ALUMINIUM', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('AA', 'ALUMINIUM', 'ANODIZED', 'NULL', 'NULL', 'NULL', 'BA');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('EA', 'ALUMINIUM', 'ENAMELLED', 'PLASTIC', 'NULL', 'PLASTIC', 'BA');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('BRO', 'BRONZE', '', 'NULL', 'NULL', 'COPPER, TIN', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('ST', 'STEEL', 'NULL', 'NULL', 'NULL', 'IRON, CARBON', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('SI', 'PURE SILVER', 'NULL', 'NULL', 'NULL', 'SILVER', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('SS', 'STERLING SILVER', 'NULL', 'NULL', 'NULL', 'COPPER', 'SI');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('CO', 'COPPER', 'NULL', 'NULL', 'NULL', 'COPPER', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('SI-FI-CO', 'COPPER', 'FILLED', 'SILVER', 'NULL', 'SILVER', 'CO');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('SI-PL-CO', 'COPPER', 'PLATED', 'SILVER', 'NULL', 'SILVER', 'CO');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('GO-PL-CO', 'COPPER', 'PLATED', 'GOLD', 'NULL', 'GOLD', 'CO');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('ZI', 'ZINC', 'NULL', 'NULL', 'NULL', 'ZINC', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('ZI-ALL', 'ZINC ALLOY', 'NULL', 'NULL', 'LEAD, NICKEL, CADMIUM', 'UNKNOWN', 'ZI');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('BRA', 'BRASS', 'NULL', 'NULL', 'NULL', 'COPPER, ZINC', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('LE', 'LEATHER', 'NULL', 'NULL', 'NULL', 'ANIMAL HIDE', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('SU', 'SUEDE', 'NULL', 'NULL', 'NULL', 'NULL', 'LE');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('FA-LE', 'FAUX LEATHER', 'NULL', 'NULL', 'NULL', 'UNKNOWN', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('FA-SU', 'FAUX SUEDE', 'NULL', 'NULL', 'NULL', 'UNKNOWN', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('OTH-STO', 'OTHER STONE', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('GEM', 'GEMSTONE', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('WOO', 'WOOD', 'NULL', 'NULL', 'NULL', 'WOOD', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('GLA', 'GLASS', 'NULL', 'NULL', 'NULL', 'GLASS', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('OTH-RUB', 'OTHER RUBBER', 'NULL', 'NULL', 'NULL', 'RUBBER', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('EPDM', 'EPDM', 'NULL', 'NULL', 'NULL', 'RUBBER', 'NULL');

INSERT INTO MATERIALS (ABBREVIATION, BASE_MATERIAL, PROCESSING, PROCESSING_MATERIAL, ALLERGENS_EXCLUDED, BASE_MATERIALS_INCLUDED, PARENT_MATERIAL) 
VALUES ('SU-SST', 'SURGICAL STAINLESS STEEL', '', 'NULL', 'NULL', 'NULL', 'SST');

-- Import Data into table MATERIALS from file J:\CarinaOneDrive\OneDrive\Documents\Boom Projects\MetalWeaves\db\mwd_git\SourceFiles\materialForWorkbench.csv . Task successful and sent to worksheet.
