SELECT C.CRAFTED_INGREDIENT_ID
, C.CRAFTED_INGREDIENT_TYPE
INTO
:P2010_CRAFTED_INGREDIENT_ID
, :P2010_CRAFTED_INGREDIENT_TYPE
FROM CRAFTED_INGREDIENTS C
WHERE C.CRAFTED_INGREDIENT_ID = :P2010_ITEM_ID;

SELECT * FROM CRAFTED_INGREDIENTS
WHERE CRAFTED_INGREDIENT_ID = :P2010_ITEM_ID;