SELECT O.OTHER_INGREDIENT_ID
, O.OTHER_INGREDIENT_TYPE
INTO
:P2010_OTHER_INGREDIENT_ID
, :P2010_OTHER_INGREDIENT_TYPE
FROM OTHER_INGREDIENTS O
WHERE O.OTHER_INGREDIENT_ID = :P2010_ITEM_ID;

SELECT * FROM OTHER_INGREDIENTS
WHERE OTHER_INGREDIENT_ID = :P2010_ITEM_ID;