DECLARE
    V_EXISTS NUMBER;
BEGIN
		SELECT COUNT(*) INTO V_EXISTS FROM KIT_ITEMS WHERE KIT_ID = :P2010_KIT_ID;
        IF V_EXISTS <> 0
            THEN
                DELETE FROM KIT_ITEMS WHERE KIT_ID = :P2010_KIT_ID;
        END IF;
        
        SELECT COUNT(*) INTO V_EXISTS FROM KITS WHERE KIT_ID = :P2010_KIT_ID;
        IF V_EXISTS <> 0
            THEN
                DELETE FROM KITS WHERE KIT_ID = :P2010_KIT_ID;
        END IF;
        
END;