SELECT C.CREATED_ITEM_ID
, C.CREATED_ITEM_TYPE
INTO
:P2010_CREATED_ITEM_ID
, :P2010_CREATED_ITEM_TYPE
FROM CREATED_ITEMS C
WHERE C.CREATED_ITEM_ID = :P2010_ITEM_ID;

SELECT * FROM CREATED_ITEMS
WHERE CREATED_ITEM_ID = :P2010_ITEM_ID;