SELECT R.RAW_INGREDIENT_ID
, R.RAW_INGREDIENT_TYPE
INTO
:P2010_RAW_INGREDIENT_ID
, :P2010_RAW_INGREDIENT_TYPE
FROM RAW_INGREDIENTS R
WHERE R.RAW_INGREDIENT_ID = :P2010_ITEM_ID;

SELECT * FROM RAW_INGREDIENTS
WHERE RAW_INGREDIENT_ID = :P2010_ITEM_ID;