DECLARE
    V_EXISTS NUMBER;
BEGIN

            SELECT COUNT(*) INTO V_EXISTS FROM WIRES WHERE WIRE_ID = :P2010_WIRE_ID;
            IF V_EXISTS <> 0
                THEN
                    DELETE FROM WIRES WHERE WIRE_ID = :P2010_WIRE_ID;
            END IF;
            
            SELECT COUNT(*) INTO V_EXISTS FROM CHAINS WHERE CHAIN_ID = :P2010_CHAIN_ID;
            IF V_EXISTS <> 0
                THEN
                    DELETE FROM CHAINS WHERE CHAIN_ID = :P2010_CHAIN_ID;
            END IF;

            SELECT COUNT(*) INTO V_EXISTS FROM LACE WHERE LACE_ID = :P2010_LACE_ID;
            IF V_EXISTS <> 0
                THEN
                    DELETE FROM LACE WHERE LACE_ID = :P2010_LACE_ID;
            END IF;

        SELECT COUNT(*) INTO V_EXISTS FROM RAW_INGREDIENTS WHERE RAW_INGREDIENT_ID = :P2010_INGREDIENT_ID;
        IF V_EXISTS <> 0
            THEN
                DELETE FROM RAW_INGREDIENTS WHERE RAW_INGREDIENT_ID = :P2010_INGREDIENT_ID;
        END IF;
        
            SELECT COUNT(*) INTO V_EXISTS FROM RINGS WHERE RING_ID = :P2010_RING_ID;
            IF V_EXISTS <> 0
                THEN
                    DELETE FROM RINGS WHERE RING_ID = :P2010_RING_ID;
            END IF;
            
            SELECT COUNT(*) INTO V_EXISTS FROM SCALES WHERE SCALE_ID = :P2010_SCALE_ID;
            IF V_EXISTS <> 0
                THEN
                    DELETE FROM SCALES WHERE SCALE_ID = :P2010_SCALE_ID;
            END IF;
        
            SELECT COUNT(*) INTO V_EXISTS FROM BEADS WHERE BEAD_ID = :P2010_BEAD_ID;
            IF V_EXISTS <> 0
                THEN
                    DELETE FROM BEADS WHERE BEAD_ID = :P2010_BEAD_ID;
            END IF;
            
            SELECT COUNT(*) INTO V_EXISTS FROM CLASPS WHERE CLASP_ID = :P2010_CLASP_ID;
            IF V_EXISTS <> 0
                THEN
                    DELETE FROM CLASPS WHERE CLASP_ID = :P2010_CLASP_ID;
            END IF;            

            SELECT COUNT(*) INTO V_EXISTS FROM ATTACHMENTS WHERE ATTACHMENT_ID = :P2010_ATTACHMENT_ID;
            IF V_EXISTS <> 0
                THEN
                    DELETE FROM ATTACHMENTS WHERE ATTACHMENT_ID = :P2010_ATTACHMENT_ID;
            END IF;            

        SELECT COUNT(*) INTO V_EXISTS FROM CRAFTED_INGREDIENTS WHERE CRAFTED_INGREDIENT_ID = :P2010_INGREDIENT_ID;
        IF V_EXISTS <> 0
            THEN
                DELETE FROM CRAFTED_INGREDIENTS WHERE CRAFTED_INGREDIENT_ID = :P2010_INGREDIENT_ID;
        END IF;
		
		SELECT COUNT(*) INTO V_EXISTS FROM OTHER_INGREDIENTS WHERE OTHER_INGREDIENT_ID = :P2010_INGREDIENT_ID;
        IF V_EXISTS <> 0
            THEN
                DELETE FROM OTHER_INGREDIENTS WHERE OTHER_INGREDIENT_ID = :P2010_INGREDIENT_ID;
        END IF;
              
		SELECT COUNT(*) INTO V_EXISTS FROM INGREDIENTS WHERE INGREDIENT_ID = :P2010_INGREDIENT_ID;
        IF V_EXISTS <> 0
            THEN
                DELETE FROM INGREDIENTS WHERE INGREDIENT_ID = :P2010_INGREDIENT_ID;
        END IF;
END;