DECLARE
    V_EXISTS NUMBER;
BEGIN
        SELECT COUNT(*) INTO V_EXISTS FROM TOOLS WHERE TOOL_ID = :P2010_TOOL_ID;
        IF V_EXISTS <> 0
            THEN
                DELETE FROM TOOLS WHERE TOOL_ID = :P2010_TOOL_ID;
        END IF;
END;