SELECT A.ATTACHMENT_ID
, A.ATTACHMENT_TYPE
INTO
:P2010_ATTACHMENT_ID
, :P2010_ATTACHMENT_TYPE
FROM ATTACHMENTS A
WHERE A.ATTACHMENT_ID = :P2010_ITEM_ID;

SELECT * FROM ATTACHMENTS
WHERE ATTACHMENT_ID = :P2010_ITEM_ID;