SELECT O.OTHER_ITEM_ID
, O.OTHER_ITEM_TYPE
INTO
:P2010_OTHER_ITEM_ID
, :P2010_OTHER_ITEM_TYPE
FROM OTHER_ITEMS O
WHERE O.OTHER_ITEM_ID = :P2010_ITEM_ID;

SELECT * FROM OTHER_ITEMS
WHERE OTHER_ITEM_ID = :P2010_ITEM_ID;