DECLARE
    V_EXISTS NUMBER;
BEGIN
		SELECT COUNT(*) INTO V_EXISTS FROM SET_ITEMS WHERE SET_ID = :P2010_SET_ID;
        IF V_EXISTS <> 0
            THEN
                DELETE FROM SET_ITEMS WHERE SET_ID = :P2010_SET_ID;
        END IF;
        
        SELECT COUNT(*) INTO V_EXISTS FROM SETS WHERE SET_ID = :P2010_SET_ID;
        IF V_EXISTS <> 0
            THEN
                DELETE FROM SETS WHERE SET_ID = :P2010_SET_ID;
        END IF;
END;