DECLARE
    V_EXISTS NUMBER;
BEGIN
     SELECT COUNT(*) INTO V_EXISTS FROM ITEM_INGREDIENTS WHERE ITEM_ID = :P2010_ITEM_ID;
        IF V_EXISTS <> 0
            THEN
                DELETE FROM ITEM_INGREDIENTS WHERE ITEM_ID = :P2010_ITEM_ID;
        END IF;
        
		SELECT COUNT(*) INTO V_EXISTS FROM ITEMS WHERE ITEM_ID = :P2010_ITEM_ID;
        IF V_EXISTS <> 0
            THEN
                DELETE FROM ITEMS WHERE ITEM_ID = :P2010_ITEM_ID;
        END IF;
END;