--------------------------------------------------------
--  File created - Tuesday-January-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MATERIALS
--------------------------------------------------------

  CREATE TABLE "MWD"."MATERIALS" 
   (	"ABBREVIATION" VARCHAR2(45 BYTE), 
	"BASE_MATERIAL" VARCHAR2(45 BYTE), 
	"PROCESSING" VARCHAR2(45 BYTE), 
	"PROCESSING_MATERIAL" VARCHAR2(45 BYTE), 
	"ALLERGENS_EXCLUDED" VARCHAR2(45 BYTE), 
	"BASE_MATERIALS_INCLUDED" VARCHAR2(2000 BYTE), 
	"PARENT_MATERIAL" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
REM INSERTING into MWD.MATERIALS
SET DEFINE OFF;
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('HIDE','ANIMAL HIDE',null,null,null,null,'HIDE');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('IR','IRON',null,null,null,null,'IR');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('CB','CARBON',null,null,null,null,'CB');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('STO','STONE',null,null,null,'STONE','STO');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('TI','TITANIUM',null,null,null,null,'TI');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('PL','PLASTIC',null,null,null,null,'PL');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('OTH','OTHER',null,null,null,null,'OTH');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('OTH-MET','OTHER METAL',null,null,null,'OTHER','OTH');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('SST','STAINLESS STEEL',null,null,null,'STEEL','ST');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('SST-BL','STAINLESS STEEL','BLACKENED',null,null,null,'SST');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('PL-SST','STAINLESS STEEL','PLATED','OTHER',null,null,'SST');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('PL-SST-TI','STAINLESS STEEL','PLATED','TITANIUM',null,'TITANIUM','SST');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('BA','BASE ALUMINIUM',null,null,null,'ALUMINIUM','BA');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('AA','ALUMINIUM','ANODIZED',null,null,null,'BA');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('EA','ALUMINIUM','ENAMELLED','PLASTIC',null,'PLASTIC','BA');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('BRO','BRONZE',null,null,null,'COPPER, TIN','BRO');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('ST','STEEL',null,null,null,'IRON, CARBON','ST');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('SI','PURE SILVER',null,null,null,'SILVER','SI');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('SS','STERLING SILVER',null,null,null,'COPPER','SI');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('CO','COPPER',null,null,null,'COPPER','CO');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('SI-FI-CO','COPPER','FILLED','SILVER',null,'SILVER','CO');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('SI-PL-CO','COPPER','PLATED','SILVER',null,'SILVER','CO');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('GO-PL-CO','COPPER','PLATED','GOLD',null,'GOLD','CO');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('ZI','ZINC',null,null,null,'ZINC','ZI');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('ZI-ALL','ZINC ALLOY',null,null,'LEAD, NICKEL, CADMIUM','OTHER','ZI');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('BRA','BRASS',null,null,null,'COPPER, ZINC','BRA');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('LE','LEATHER',null,null,null,'ANIMAL HIDE','HIDE');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('SU','SUEDE',null,null,null,'ANIMAL HIDE','LE');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('FA-LE','FAUX LEATHER',null,null,null,'OTHER','OTH');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('FA-SU','FAUX SUEDE',null,null,null,'OTHER','OTH');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('OTH-STO','OTHER STONE',null,null,null,'STONE','STO');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('GEM','GEMSTONE',null,null,null,'STONE','STO');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('WOO','WOOD',null,null,null,'WOOD','WOO');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('GLA','GLASS',null,null,null,'GLASS','GLA');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('RUB','RUBBER',null,null,null,'RUBBER','RUB');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('EPDM','EPDM',null,null,null,'RUBBER','RUB');
Insert into MWD.MATERIALS (ABBREVIATION,BASE_MATERIAL,PROCESSING,PROCESSING_MATERIAL,ALLERGENS_EXCLUDED,BASE_MATERIALS_INCLUDED,PARENT_MATERIAL) values ('SU-SST','SURGICAL STAINLESS STEEL',null,null,null,null,'SST');
--------------------------------------------------------
--  DDL for Index MATERIALS_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "MWD"."MATERIALS_UN" ON "MWD"."MATERIALS" ("PROCESSING_MATERIAL", "PROCESSING", "BASE_MATERIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Index MATERIALS_PK
--------------------------------------------------------

  CREATE INDEX "MWD"."MATERIALS_PK" ON "MWD"."MATERIALS" ("ABBREVIATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Trigger MATERIALS_JNTRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MWD"."MATERIALS_JNTRG" 
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON MWD.MATERIALS for each row 
 Declare 
  rec MWD.MATERIALS_JN%ROWTYPE; 
  blank MWD.MATERIALS_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.ABBREVIATION := :NEW.ABBREVIATION; 
      rec.BASE_MATERIAL := :NEW.BASE_MATERIAL; 
      rec.PROCESSING := :NEW.PROCESSING; 
      rec.PROCESSING_MATERIAL := :NEW.PROCESSING_MATERIAL; 
      rec.ALLERGENS_EXCLUDED := :NEW.ALLERGENS_EXCLUDED; 
      rec.BASE_MATERIALS_INCLUDED := :NEW.BASE_MATERIALS_INCLUDED; 
      rec.PARENT_MATERIAL := :NEW.PARENT_MATERIAL; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.ABBREVIATION := :OLD.ABBREVIATION; 
      rec.BASE_MATERIAL := :OLD.BASE_MATERIAL; 
      rec.PROCESSING := :OLD.PROCESSING; 
      rec.PROCESSING_MATERIAL := :OLD.PROCESSING_MATERIAL; 
      rec.ALLERGENS_EXCLUDED := :OLD.ALLERGENS_EXCLUDED; 
      rec.BASE_MATERIALS_INCLUDED := :OLD.BASE_MATERIALS_INCLUDED; 
      rec.PARENT_MATERIAL := :OLD.PARENT_MATERIAL; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into MWD.MATERIALS_JN VALUES rec; 
  END; 

/
ALTER TRIGGER "MWD"."MATERIALS_JNTRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIALS
--------------------------------------------------------

  ALTER TABLE "MWD"."MATERIALS" ADD CONSTRAINT "MATERIALS_PK" PRIMARY KEY ("ABBREVIATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP"  ENABLE;
  ALTER TABLE "MWD"."MATERIALS" MODIFY ("ABBREVIATION" NOT NULL ENABLE);
  ALTER TABLE "MWD"."MATERIALS" ADD CONSTRAINT "MATERIALS_UN" UNIQUE ("PROCESSING_MATERIAL", "PROCESSING", "BASE_MATERIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP"  ENABLE;
