--------------------------------------------------------
--  File created - Tuesday-January-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STANDARD_WIRE_GAUGES
--------------------------------------------------------

  CREATE TABLE "MWD"."STANDARD_WIRE_GAUGES" 
   (	"SWG_ID" NUMBER, 
	"SWG" VARCHAR2(30 BYTE), 
	"INCH_DIAMETER" NUMBER(10,4), 
	"DIAMETER_MM" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
REM INSERTING into MWD.STANDARD_WIRE_GAUGES
SET DEFINE OFF;
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('1','7/0','0,5','12,7');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('2','6/0','0,464','11,786');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('3','5/0','0,432','10,973');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('4','4/0','0,4','10,16');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('5','3/0','0,372','9,449');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('6','2/0','0,348','8,839');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('7','0','0,324','8,23');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('8','1','0,3','7,62');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('9','2','0,276','7,01');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('10','3','0,252','6,401');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('11','4','0,232','5,893');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('12','5','0,212','5,385');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('13','6','0,192','4,877');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('14','7','0,176','4,47');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('15','8','0,16','4,064');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('16','9','0,144','3,658');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('17','10','0,128','3,251');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('18','11','0,116','2,946');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('19','12','0,104','2,642');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('20','13','0,092','2,337');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('21','14','0,08','2,032');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('22','15','0,072','1,829');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('23','16','0,064','1,626');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('24','17','0,056','1,422');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('25','18','0,048','1,219');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('26','19','0,04','1,016');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('27','20','0,036','0,914');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('28','21','0,032','0,813');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('29','22','0,028','0,711');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('30','23','0,024','0,61');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('31','24','0,022','0,559');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('32','25','0,02','0,508');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('33','26','0,018','0,4572');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('34','27','0,0164','0,4166');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('35','28','0,0148','0,3759');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('36','29','0,0136','0,3454');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('37','30','0,0124','0,315');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('38','31','0,0116','0,2946');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('39','32','0,0108','0,2743');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('40','33','0,01','0,254');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('41','34','0,0092','0,2337');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('42','35','0,0084','0,2134');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('43','36','0,0076','0,193');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('44','37','0,0068','0,1727');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('45','38','0,006','0,1524');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('46','39','0,0052','0,1321');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('47','40','0,0048','0,1219');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('48','41','0,0044','0,1118');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('49','42','0,004','0,1016');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('50','43','0,0036','0,0914');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('51','44','0,0032','0,0813');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('52','45','0,0028','0,0711');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('53','46','0,0024','0,061');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('54','47','0,002','0,0508');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('55','48','0,0016','0,0406');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('56','49','0,0012','0,0305');
Insert into MWD.STANDARD_WIRE_GAUGES (SWG_ID,SWG,INCH_DIAMETER,DIAMETER_MM) values ('57','50','0,001','0,0254');
--------------------------------------------------------
--  DDL for Index STANDARD_WIRE_GAUGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MWD"."STANDARD_WIRE_GAUGE_PK" ON "MWD"."STANDARD_WIRE_GAUGES" ("SWG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Index STANDARD_WIRE_GAUGE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MWD"."STANDARD_WIRE_GAUGE_UK" ON "MWD"."STANDARD_WIRE_GAUGES" ("SWG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Trigger STANDARD_WIRE_GAUGES_JNTRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MWD"."STANDARD_WIRE_GAUGES_JNTRG" 
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON MWD.STANDARD_WIRE_GAUGES for each row 
 Declare 
  rec MWD.STANDARD_WIRE_GAUGES_JN%ROWTYPE; 
  blank MWD.STANDARD_WIRE_GAUGES_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.SWG_ID := :NEW.SWG_ID; 
      rec.SWG := :NEW.SWG; 
      rec.INCH_DIAMETER := :NEW.INCH_DIAMETER; 
      rec.DIAMETER_MM := :NEW.DIAMETER_MM; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.SWG_ID := :OLD.SWG_ID; 
      rec.SWG := :OLD.SWG; 
      rec.INCH_DIAMETER := :OLD.INCH_DIAMETER; 
      rec.DIAMETER_MM := :OLD.DIAMETER_MM; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into MWD.STANDARD_WIRE_GAUGES_JN VALUES rec; 
  END;
/
ALTER TRIGGER "MWD"."STANDARD_WIRE_GAUGES_JNTRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table STANDARD_WIRE_GAUGES
--------------------------------------------------------

  ALTER TABLE "MWD"."STANDARD_WIRE_GAUGES" ADD CONSTRAINT "STANDARD_WIRE_GAUGE_UK" UNIQUE ("SWG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP"  ENABLE;
  ALTER TABLE "MWD"."STANDARD_WIRE_GAUGES" ADD CONSTRAINT "STANDARD_WIRE_GAUGE_PK" PRIMARY KEY ("SWG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP"  ENABLE;
  ALTER TABLE "MWD"."STANDARD_WIRE_GAUGES" MODIFY ("SWG_ID" NOT NULL ENABLE);
