--------------------------------------------------------
--  File created - Tuesday-January-15-2019   
--------------------------------------------------------
DROP TABLE "MWD"."WEAVE_ARS" cascade constraints;
DROP TABLE "MWD"."WEAVES" cascade constraints;
DROP TABLE "MWD"."WEAVE_ARS_JN" cascade constraints;
--------------------------------------------------------
--  DDL for Table WEAVE_ARS
--------------------------------------------------------

  CREATE TABLE "MWD"."WEAVE_ARS" 
   (	"WEAVE_AR_ID" NUMBER, 
	"WEAVE_ID" NUMBER, 
	"OPTIMAL_AR" NUMBER(8,2), 
	"MIN_AR" NUMBER(8,2), 
	"MAX_AR" NUMBER(8,2), 
	"AR_SORT_ORDER" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Table WEAVES
--------------------------------------------------------

  CREATE TABLE "MWD"."WEAVES" 
   (	"WEAVE_ID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"SYNONYMS" VARCHAR2(2000 BYTE), 
	"PARENT_WEAVE_ID" NUMBER, 
	"COMPLEXITY" VARCHAR2(30 BYTE) DEFAULT 'BEGINNER', 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"SPEED_WEAVE" VARCHAR2(2000 BYTE), 
	"SOURCE_URL" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Table WEAVE_ARS_JN
--------------------------------------------------------

  CREATE TABLE "MWD"."WEAVE_ARS_JN" 
   (	"JN_OPERATION" CHAR(3 BYTE), 
	"JN_ORACLE_USER" VARCHAR2(30 BYTE), 
	"JN_DATETIME" DATE, 
	"JN_NOTES" VARCHAR2(240 BYTE), 
	"JN_APPLN" VARCHAR2(35 BYTE), 
	"JN_SESSION" NUMBER(38,0), 
	"WEAVE_AR_ID" NUMBER, 
	"WEAVE_ID" NUMBER, 
	"OPTIMAL_AR" NUMBER(8,2), 
	"MIN_AR" NUMBER(8,2), 
	"MAX_AR" NUMBER(8,2), 
	"AR_SORT_ORDER" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
REM INSERTING into MWD.WEAVE_ARS
SET DEFINE OFF;
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('1','1','3,55','3,2','3,9','1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('2','2','3,2',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('3','3','4,3',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('4','4','4,9',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('5','5','2,1','2',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('6','6','2,1','2',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('8','8','2,1','2',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('9','9','2,1','2',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('10','10','2,2',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('11','10','4,1',null,null,'2');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('12','11','3,5','2,83',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('13','12','4,9','4,25',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('14','13','3,3',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('15','14','4',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('16','14','6,2',null,null,'2');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('17','15','4,3','3,9','5','1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('18','16','7','5,7',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('19','17','5,5','4,8',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('20','18','4,3','3,5',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('21','31','3,5','3,2','4','1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('22','19','5,5','5,2','5,8','1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('23','19','2,8','2,6','4,3','2');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('24','20','3,3','2,9',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('25','20','2,1','2',null,'2');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('26','21','3,9',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('27','32','9,9','2',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('28','22','5,1','3,8',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('29','23','4,2','3,7',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('30','24','3,5',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('31','25','2,9','2,7','3,2','1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('32','26','4',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('33','27','5,3','5,1',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('34','27','3,3','2',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('35','28','2,7','2,6','2,9','1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('36','29','3,83','3,6','4','1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('37','30','4,3','4,1','4,5','1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('38','36','6,25',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('39','36','4,18',null,null,'2');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('40','33','5','4,4','5,4','1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('41','34','4',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('42','35','4,9','4,6','5,3','1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('43','38','4,2','4',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('44','39','3,3',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('45','40','5,3','5,2',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('46','41','4',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('47','37','5,6','4,7',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('48','42','3,1',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('49','45','6,1','5,7','6,5','1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('50','45','3,9','3,7','4,6','2');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('52','44','4,6','3,5',null,'2');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('54','43','3,9','3,5',null,'2');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('55','46','4,5',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('56','46','3,1',null,null,'2');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('57','47','4','3,8',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('58','48','4,7','4,1',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('59','50','7',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('60','51','4','4,16',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('61','52','5','4,6',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('62','53','7,8','5,2',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('63','54','5',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('64','55','5,5',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('65','55','3,3',null,null,'2');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('66','56','4,8','4,6','5','1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('67','49','5,2',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('68','49','6,5',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('7','7','2,1','2',null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('51','44','6,5',null,null,'1');
Insert into MWD.WEAVE_ARS (WEAVE_AR_ID,WEAVE_ID,OPTIMAL_AR,MIN_AR,MAX_AR,AR_SORT_ORDER) values ('53','43','5,9',null,null,'1');
--------------------------------------------------------
--  DDL for Index WEAVE_ARS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MWD"."WEAVE_ARS_PK" ON "MWD"."WEAVE_ARS" ("WEAVE_AR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Index WEAVE_ARS_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MWD"."WEAVE_ARS_UK" ON "MWD"."WEAVE_ARS" ("WEAVE_ID", "OPTIMAL_AR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Trigger WEAVE_ARS_BRIU
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MWD"."WEAVE_ARS_BRIU" 
    BEFORE INSERT OR UPDATE ON MWD.WEAVE_ARS 
    FOR EACH ROW 
DECLARE 
  weave_ar_order number; 
  weav_ar_id number; 
BEGIN 
  if inserting then   
    if :new.weave_ar_id is null then 
      select weav_ar_seq.nextval 
        into weav_ar_id 
        from dual; 
      :new.weave_ar_id := weav_ar_id; 
    end if; 

    if :new.ar_sort_order is null then 
      select nvl(max(ar_sort_order), 0)
	  into weave_ar_order
	  from weave_ars
	  where weave_id=:new.weave_id;

      :new.ar_sort_order := weave_ar_order +1; 
    end if; 
  end if; 
END; 

/
ALTER TRIGGER "MWD"."WEAVE_ARS_BRIU" ENABLE;
--------------------------------------------------------
--  DDL for Trigger WEAVE_ARS_JNTRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MWD"."WEAVE_ARS_JNTRG" 
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON MWD.WEAVE_ARS for each row 
 Declare 
  rec MWD.WEAVE_ARS_JN%ROWTYPE; 
  blank MWD.WEAVE_ARS_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.WEAVE_AR_ID := :NEW.WEAVE_AR_ID; 
      rec.WEAVE_ID := :NEW.WEAVE_ID; 
      rec.OPTIMAL_AR := :NEW.OPTIMAL_AR; 
      rec.MIN_AR := :NEW.MIN_AR; 
      rec.MAX_AR := :NEW.MAX_AR; 
      rec.AR_SORT_ORDER := :NEW.AR_SORT_ORDER; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.WEAVE_AR_ID := :OLD.WEAVE_AR_ID; 
      rec.WEAVE_ID := :OLD.WEAVE_ID; 
      rec.OPTIMAL_AR := :OLD.OPTIMAL_AR; 
      rec.MIN_AR := :OLD.MIN_AR; 
      rec.MAX_AR := :OLD.MAX_AR; 
      rec.AR_SORT_ORDER := :OLD.AR_SORT_ORDER; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into MWD.WEAVE_ARS_JN VALUES rec; 
  END; 

/
ALTER TRIGGER "MWD"."WEAVE_ARS_JNTRG" ENABLE;
--------------------------------------------------------
--  DDL for Synonymn DUAL
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DUAL" FOR "SYS"."DUAL";
--------------------------------------------------------
--  Constraints for Table WEAVE_ARS
--------------------------------------------------------

  ALTER TABLE "MWD"."WEAVE_ARS" ADD CONSTRAINT "WEAVE_ARS_UK" UNIQUE ("WEAVE_ID", "OPTIMAL_AR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP"  ENABLE;
  ALTER TABLE "MWD"."WEAVE_ARS" ADD CONSTRAINT "WEAVE_ARS_PK" PRIMARY KEY ("WEAVE_AR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP"  ENABLE;
  ALTER TABLE "MWD"."WEAVE_ARS" MODIFY ("WEAVE_ID" NOT NULL ENABLE);
  ALTER TABLE "MWD"."WEAVE_ARS" MODIFY ("WEAVE_AR_ID" NOT NULL ENABLE);
