--------------------------------------------------------
--  File created - Tuesday-January-15-2019   
--------------------------------------------------------
DROP TABLE "MWD"."COLORS" cascade constraints;
DROP TABLE "MWD"."COLORS_JN" cascade constraints;
--------------------------------------------------------
--  DDL for Table COLORS
--------------------------------------------------------

  CREATE TABLE "MWD"."COLORS" 
   (	"NAME" VARCHAR2(45 BYTE), 
	"BASE_COLOR" VARCHAR2(45 BYTE), 
	"TINT" VARCHAR2(45 BYTE), 
	"COLOR_TYPE" VARCHAR2(45 BYTE), 
	"ADDED_COLOR" VARCHAR2(45 BYTE), 
	"PARENT_COLOR" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Table COLORS_JN
--------------------------------------------------------

  CREATE TABLE "MWD"."COLORS_JN" 
   (	"JN_OPERATION" CHAR(3 BYTE), 
	"JN_ORACLE_USER" VARCHAR2(30 BYTE), 
	"JN_DATETIME" DATE, 
	"JN_NOTES" VARCHAR2(240 BYTE), 
	"JN_APPLN" VARCHAR2(35 BYTE), 
	"JN_SESSION" NUMBER(38,0), 
	"NAME" VARCHAR2(45 BYTE), 
	"BASE_COLOR" VARCHAR2(45 BYTE), 
	"TINT" VARCHAR2(45 BYTE), 
	"COLOR_TYPE" VARCHAR2(45 BYTE), 
	"ADDED_COLOR" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
REM INSERTING into MWD.COLORS
SET DEFINE OFF;
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('NATURAL','NATURAL','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('COLOR MIX','COLOR MIX','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('RAINBOW','RAINBOW','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('RED','RED','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('PURPLE','PURPLE','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('GREEN','GREEN','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('ORANGE','ORANGE','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('PINK','PINK','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('YELLOW','YELLOW','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('BLUE','BLUE','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('BROWN','BROWN','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('BLACK','BLACK','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('SILVER','SILVER','NORMAL','SHINY',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('BEIGE','BEIGE','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('BLACKENED STAINLESS','STAINLESS STEEL','NORMAL','MATTE','BLACK',null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('COFFEE BROWN','BROWN','NORMAL','MATTE','COFFEE',null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('DEEP RED','RED','DARK','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('BLACK SILVER','SILVER','NORMAL','MATTE','BLACK',null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('DARK COFFEE BROWN','BROWN','DARK','MATTE','COFFEE',null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('DARK GREEN','GREEN','DARK','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('DARK BLUE STEEL','STEEL','DARK','MATTE','BLUE',null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('PURPLE RED','RED','NORMAL','MATTE','PURPLE',null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('TURQUOISE','TURQUOISE','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('LIGHT BROWN','BROWN','LIGHT','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('SHINY RED','RED','NORMAL','SHINY',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('SHINY STEEL','STEEL','NORMAL','SHINY',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('SHINY PURPLE','PURPLE','NORMAL','SHINY',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('GOLD','GOLD','NORMAL','SHINY',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('SHINY ORANGE','ORANGE','NORMAL','SHINY',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('SHINY GREEN','GREEN','NORMAL','SHINY',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('SHINY LIGHT BLUE','BLUE','LIGHT','SHINY',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('SHINY BLUE','BLUE','NORMAL','SHINY',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('NEW BRONZE','BRONZE','NORMAL','SHINY',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('ANTIQUE BRONZE','BRONZE','NORMAL','MATTE',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('BRASS','BRASS','NORMAL','SHINY',null,null);
Insert into MWD.COLORS (NAME,BASE_COLOR,TINT,COLOR_TYPE,ADDED_COLOR,PARENT_COLOR) values ('COPPER','COPPER','NORMAL','SHINY',null,null);
--------------------------------------------------------
--  DDL for Index COLORS_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "MWD"."COLORS_UN" ON "MWD"."COLORS" ("TINT", "COLOR_TYPE", "ADDED_COLOR", "BASE_COLOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Index COLORS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MWD"."COLORS_PK" ON "MWD"."COLORS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Trigger COLORS_JNTRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MWD"."COLORS_JNTRG" 
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON MWD.COLORS for each row 
 Declare 
  rec MWD.COLORS_JN%ROWTYPE; 
  blank MWD.COLORS_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.NAME := :NEW.NAME; 
      rec.BASE_COLOR := :NEW.BASE_COLOR; 
      rec.TINT := :NEW.TINT; 
      rec.COLOR_TYPE := :NEW.COLOR_TYPE; 
      rec.ADDED_COLOR := :NEW.ADDED_COLOR; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.NAME := :OLD.NAME; 
      rec.BASE_COLOR := :OLD.BASE_COLOR; 
      rec.TINT := :OLD.TINT; 
      rec.COLOR_TYPE := :OLD.COLOR_TYPE; 
      rec.ADDED_COLOR := :OLD.ADDED_COLOR; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into MWD.COLORS_JN VALUES rec; 
  END; 

/
ALTER TRIGGER "MWD"."COLORS_JNTRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table COLORS
--------------------------------------------------------

  ALTER TABLE "MWD"."COLORS" ADD CONSTRAINT "COLORS_UN" UNIQUE ("TINT", "COLOR_TYPE", "ADDED_COLOR", "BASE_COLOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP"  ENABLE;
  ALTER TABLE "MWD"."COLORS" ADD CONSTRAINT "COLORS_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP"  ENABLE;
  ALTER TABLE "MWD"."COLORS" MODIFY ("NAME" NOT NULL ENABLE);
