--------------------------------------------------------
--  File created - Tuesday-January-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONVERSION_FACTORS
--------------------------------------------------------

  CREATE TABLE "MWD"."CONVERSION_FACTORS" 
   (	"NAME_OF_UNIT" VARCHAR2(45 BYTE), 
	"SYMBOL" VARCHAR2(45 BYTE), 
	"DEFINITION" VARCHAR2(500 BYTE), 
	"METER_FACTOR" VARCHAR2(100 BYTE), 
	"CONVERSION_TYPE" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
REM INSERTING into MWD.CONVERSION_FACTORS
SET DEFINE OFF;
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('ångström','Å','1*10^-10 m','1.00E-10','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('astronomical unit','AU','149597870700 m approx. Distance from Earth to Sun','1.50E+11','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('attometre','am','1*10^-18 m','1.00E-18','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('barleycorn (H)','barleycorn (H)','1/3 in (see note above about rounding)','0.00846','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('bohr, atomic unit of length','a0','Bohr radius of hydrogen','5.29E-11','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('cable length (imperial)','cable length (imperial)','608 ft','185.3184','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('cable length (International)','cable length (International)','1/10 nmi','185.2','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('cable length (US)','cable length (US)','720 ft','219.456','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('chain (Gunter; Surveyor)','ch','66 ft (US) equals 4 rods','20.11684','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('cubit (H)','cubit (H)','Distance from fingers to elbow approx. 18 in','0.5','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('ell (H)','ell','45 in (In England usually)','1.143','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('fathom','ftm','6 ft','1.8288','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('femtometre','fm','1*10^-15 m','1.00E-15','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('fermi','fm','1*10^-15 m','1.00E-15','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('finger','finger','7/8 in','0.022225','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('finger (cloth)','finger','4 1/2 in','0.1143','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('foot (Benoît) (H)','ft (Ben)',null,'0.304799735','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('foot (Cape) (H)','ft (Ca)','Legally defined as 1.033 English feet in 1859','0.314858','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('foot (Clarke) (H)','ft (Cla)',null,'0.304797265','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('foot (Indian) (H)','ft Ind',null,'0.304799514','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('foot, metric','mf','root of 1/10 m','0.316227766','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('foot, metric (long)','lmf','1/3 m','0.3','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('foot, metric (short)','smf','0.30 m','0.3','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('foot (International)','ft','0.3048 m equals 1/3 yd equals 12 inches','0.3048','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('foot (Sear) (H)','ft (Sear)',null,'0.30479947','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('foot (US Survey)','ft (US)','1200/3937 m','0.30480061','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('french; charriere','F','1/3 mm','0.0003','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('furlong','fur','10 chains equals 660 ft equals 220 yd','201.168','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('hand','hand','4 in','0.1016','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('inch (International)','in','2.54 cm equals 1/36 yd equals 1/12 ft','0.0254','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('league (land)','lea','approx. equals 1 hour walk, Currently defined in US as 3 Statute miles, but historically varied from 2 to 9 km','4828','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('light-day','light-day','24 light-hours','2623.879526','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('light-hour','light-hour','60 light-minutes','1092.203883','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('light-minute','light-minute','60 light-seconds','1816.742295','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('light-second','light-second','Distance light travels in one second in vacuum','299792458','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('light-year','ly','Distance light travels in vacuum in 365.25 days','9.46E+15','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('line','ln','1/12 in','0.002116','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('link (Gunter; Surveyor)','lnk','1/100 ch 0.66 ft (US) equals 7.92 in','0.2011684','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('link (Ramsden; Engineer)','lnk','1 ft','0.3048','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('metre (SI base unit) (meter)','m','Distance light travels in 1/299792458 of a second in vacuum. approx. equals 1/10000000 of the distance from equator to pole.','1','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('mickey','mickey','1/200 in','0.000127','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('micrometre (old: micron)','UNISTR(''''\00B5''''); UNISTR(''''\00B5m'''')','1*10^-6 m','0.000001','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('mil; thou','mil','1*10^-3 in','0.0000254','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('mil (Sweden and Norway)','mil','10 km','10000','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('mile (geographical) (H)','mile (geographical) (H)',' 6082 ft','1853.7936','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('mile (international)','mi','80 chains equals 5280 ft equals 1760 yd','1609.344','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('mile (tactical or data)','mile (tactical or data)','6000 ft','1828.8','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('mile (telegraph) (H)','mi','6087 ft','1855.3176','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('mile (US Survey)','mi','5280 US Survey feet equals (5280* 1200/3937) m','1609.347219','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('nail (cloth)','nail (cloth)','2 1/4 in','0.05715','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('nanometre','nm','1*10^-9 m','0.000000001','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('nautical league','NL; nl','3 nmi','5556','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('nautical mile (Admiralty)','NM (Adm); nmi (Adm)','6080 ft','1853.184','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('nautical mile (international)','NM; nmi','1852 m','1852','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('nautical mile (US pre 1954)','nautical mile (US pre 1954)','1853.248 m','1853.248','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('pace','pace','2.5 ft','0.762','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('palm','palm','3 in','0.0762','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('parsec','pc','648000/pi AU; Distant point with a parallax shift of one arc second from a base of one astronomical unit. ','3.09E+16','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('pica','pica','12 points','0.00451128','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('picometre','pm','1*10^-12 m','1.00E-12','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('point (American, English)','pt','1/72.272 in','0.00035145','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('point (Didot; European)','pt','1/12 * 1/72 of pied du roi (0.00037597 m); After 1878: 5/133 cm','0.00037594','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('point (PostScript)','pt','1/72 in','0.0003527','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('point (TeX)','pt','1/72.27 in','0.00035146','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('quarter','quarter','1/4 yd','0.2286','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('rod; pole; perch (H)','rd','16 1/2 ft','5.0292','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('rope (H)','rope','20 ft','6.096','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('shaku (Japan)','shaku (Japan)','10/33 m','0.3030303','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('span (H)','span (H)','9 in','0.2286','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('spat','spat',null,'1012','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('stick (H)','stick (H)','2 in','0.0508','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('toise (French, post 1667) (H)','T','27000/13853 m','1.9490363','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('twip','twp','1/1440 in','0.000017638','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('x unit; siegbahn','xu',null,'1.00E-13','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('yard (International)','yd','0.9144 m equals 3 ft equals 36 in','0.9144','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('yoctometre','ym','1*10^-24 m','1.00E-24','LENGTH');
Insert into MWD.CONVERSION_FACTORS (NAME_OF_UNIT,SYMBOL,DEFINITION,METER_FACTOR,CONVERSION_TYPE) values ('zeptometre','zm','1*10^-21 m','1.00E-21','LENGTH');
--------------------------------------------------------
--  DDL for Index CONVERSION_FACTORS_IX
--------------------------------------------------------

  CREATE INDEX "MWD"."CONVERSION_FACTORS_IX" ON "MWD"."CONVERSION_FACTORS" ("CONVERSION_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Index CONVERSION_FACTORS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MWD"."CONVERSION_FACTORS_PK" ON "MWD"."CONVERSION_FACTORS" ("NAME_OF_UNIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  Constraints for Table CONVERSION_FACTORS
--------------------------------------------------------

  ALTER TABLE "MWD"."CONVERSION_FACTORS" ADD CONSTRAINT "CONVERSION_FACTORS_PK" PRIMARY KEY ("NAME_OF_UNIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP"  ENABLE;
  ALTER TABLE "MWD"."CONVERSION_FACTORS" MODIFY ("NAME_OF_UNIT" NOT NULL ENABLE);
