--------------------------------------------------------
--  File created - Tuesday-January-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DOMAINS
--------------------------------------------------------

  CREATE TABLE "MWD"."DOMAINS" 
   (	"DOMAIN_VALUE_ID" NUMBER, 
	"DOMAIN_VALUE" VARCHAR2(100 BYTE), 
	"DOMAIN_NAME" VARCHAR2(100 BYTE), 
	"DOMAIN_REFLOC" VARCHAR2(100 BYTE) DEFAULT 'UNKNOWN', 
	"SORT_ORDER" NUMBER, 
	"PARENT_DOMAIN_VALUE_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"DOMAIN_TYPE" VARCHAR2(30 BYTE) DEFAULT 'LIST_OF_VALUES', 
	"ACTIVE" CHAR(1 BYTE) DEFAULT 'Y', 
	"USER_CREATED" VARCHAR2(30 BYTE), 
	"DATE_CREATED" DATE, 
	"USER_MODIFIED" VARCHAR2(30 BYTE), 
	"DATE_MODIFIED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
REM INSERTING into MWD.DOMAINS
SET DEFINE OFF;
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('450','PERSON','TYPE','DOMAINS','5',null,null,'LIST_OF_VALUES','Y','MWD',to_date('08.12.18','DD.MM.RR'),'MWD',to_date('08.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('451','NATURAL_PERSON','PERSON_TYPE','PERSONS','1','450',null,'LIST_OF_VALUES','Y','MWD',to_date('08.12.18','DD.MM.RR'),'MWD',to_date('08.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('452','LEGAL_PERSON','PERSON_TYPE','PERSONS','2','450',null,'LIST_OF_VALUES','Y','MWD',to_date('08.12.18','DD.MM.RR'),'MWD',to_date('08.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('500','BOOLEAN','LABEL','DOMAINS','1',null,null,'LIST_OF_VALUES','Y','MWD',to_date('09.12.18','DD.MM.RR'),'MWD',to_date('09.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('501','TRUE','BOOLEAN_LABEL','MULTIPLE','1','500',null,'LIST_OF_VALUES','Y','MWD',to_date('09.12.18','DD.MM.RR'),'MWD',to_date('09.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('502','FALSE','BOOLEAN_LABEL','MULTIPLE','2','500',null,'LIST_OF_VALUES','Y','MWD',to_date('09.12.18','DD.MM.RR'),'MWD',to_date('09.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('254','HOME','ADDRESS_TYPE','LOCATION_ADDRESSES','4','250',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('255','OTHER','ADDRESS_TYPE','LOCATION_ADDRESSES','5','250',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1','DOMAIN','TYPE','DOMAINS','1',null,null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('2','LIST_OF_VALUES','DOMAIN_TYPE','DOMAINS','2','1',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('3','CONSTANT','DOMAIN_TYPE','DOMAINS','2','1',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('10','DOMAIN','DOMAINS','DOMAINS','1',null,null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'ANONYMOUS',to_date('13.01.19','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('11','Y','DOMAIN_ACTIVE','DOMAINS','1','10',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'ANONYMOUS',to_date('08.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('12','N','DOMAIN_ACTIVE','DOMAINS','2','10',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('50','ITEM','AVAILABILITY','DOMAINS','1',null,null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('51','IN_STOCK','ITEM_AVAILABILITY','ITEMS','1','50',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('52','OUT_OF_STOCK','ITEM_AVAILABILITY','ITEMS','2','50',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('100','ITEM','SALE_STATUS','DOMAINS','1',null,null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('101','NONE','ITEM_SALE_STATUS','ITEM_DETAILS','1','100',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('102','FOR_SALE','ITEM_SALE_STATUS','ITEM_DETAILS','2','100',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('103','SOLD','ITEM_SALE_STATUS','ITEM_DETAILS','3','100',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('105','BACKORDER','ITEM_SALE_STATUS','ITEM_DETAILS','4','100',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('150','WEAVE','COMPLEXITY','DOMAINS','1',null,null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('151','BEGINNER','WEAVE_COMPLEXITY','WEAVES','1','150',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('152','INTERMEDIATE','WEAVE_COMPLEXITY','WEAVES','2','150',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('153','EXPERT','WEAVE_COMPLEXITY','WEAVES','3','150',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('250','ADDRESS','TYPE','DOMAINS','2',null,null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('251','STORAGE','ADDRESS_TYPE','LOCATION_ADDRESSES','1','250',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('252','ESTABLISHMENT','ADDRESS_TYPE','LOCATION_ADDRESSES','2','250',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('253','ONLINE','ADDRESS_TYPE','LOCATION_ADDRESSES','3','250',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('300','ORDER','TYPE','DOMAINS','3',null,null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('301','PURCHASE','ORDER_TYPE','ORDERS','1','300',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('302','SALE','ORDER_TYPE','ORDERS','2','300',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('350','ORDER','STATUS','DOMAINS','1',null,null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('351','ORDERED','ORDER_STATUS','ORDERS','1','350',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('353','CANCELLED','ORDER_STATUS','ORDERS','4','350',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('352','PAID','ORDER_STATUS','ORDERS','2','350',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('354','COMPLETED','ORDER_STATUS','ORDERS','5','350',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('400','ORDER_ITEM','STATUS','DOMAINS','2',null,null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('401','TO_DELIVER','ITEM_STATUS','ORDER_ITEMS','1','400',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('402','DELIVERED','ITEM_STATUS','ORDER_ITEMS','2','400',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('403','CANCELLED','ITEM_STATUS','ORDER_ITEMS','3','400',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1000','ITEM','TYPE','DOMAINS','4',null,null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1100','OTHER','ITEM_TYPE','ITEMS','1','1000',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1200','KIT','ITEM_TYPE','ITEMS','2','1000',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1300','SET','ITEM_TYPE','ITEMS','3','1000',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1400','TOOL','ITEM_TYPE','ITEMS','4','1000',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1500','CREATED_ITEM','ITEM_TYPE','ITEMS','5','1000',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1750','INGREDIENT','ITEM_TYPE','ITEMS','6','1000',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1110','OTHER','OTHER_ITEM_TYPE','OTHER_ITEMS','1','1100',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1120','ITEM_ORDER','OTHER_ITEM_TYPE','OTHER_ITEMS','2','1100',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1210','KIT_ORDER','KIT_TYPE','KITS','1','1200',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1220','KIT_MAKE','KIT_TYPE','KITS','2','1200',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1310','SET_ORDER','SET_TYPE','SETS','1','1300',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1320','SET_MAKE','SET_TYPE','SETS','2','1300',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1410','OTHER','TOOL_TYPE','TOOLS','1','1400',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1420','PLIERS','TOOL_TYPE','TOOLS','2','1400',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1430','CALIPER','TOOL_TYPE','TOOLS','3','1400',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1440','BOX','TOOL_TYPE','TOOLS','4','1400',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1450','MAGNIFYING_GLASS','TOOL_TYPE','TOOLS','5','1400',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1460','RUBBER_COATING','TOOL_TYPE','TOOLS','6','1400',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1525','OTHER','CREATED_ITEM_TYPE','CREATED_ITEMS','1','1500',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1550','JEWELRY','CREATED_ITEM_TYPE','CREATED_ITEMS','2','1500',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1575','ACCESSORY','CREATED_ITEM_TYPE','CREATED_ITEMS','3','1500',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1600','ORNAMENT','CREATED_ITEM_TYPE','CREATED_ITEMS','4','1500',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1551','OTHER','JEWELRY_TYPE','JEWELRY','1','1550',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1552','BRACELET','JEWELRY_TYPE','JEWELRY','2','1550',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1553','NECKLACE','JEWELRY_TYPE','JEWELRY','3','1550',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1554','PENDANT','JEWELRY_TYPE','JEWELRY','4','1550',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1555','CHOKER','JEWELRY_TYPE','JEWELRY','5','1550',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1556','EARRINGS','JEWELRY_TYPE','JEWELRY','6','1550',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1576','OTHER','ACCESSORY_TYPE','ACCESSORIES','1','1575',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1577','KEYCHAIN','ACCESSORY_TYPE','ACCESSORIES','2','1575',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1578','HAIRCLIP','ACCESSORY_TYPE','ACCESSORIES','3','1575',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1579','BROOCH','ACCESSORY_TYPE','ACCESSORIES','4','1575',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1580','BOOKMARK','ACCESSORY_TYPE','ACCESSORIES','5','1575',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1601','OTHER','ORNAMENT_TYPE','ORNAMENTS','1','1600',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1602','CHRISTMAS_TREE_HANGER','ORNAMENT_TYPE','ORNAMENTS','2','1600',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1800','OTHER','INGREDIENT_TYPE','INGREDIENTS','1','1750',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1850','RAW_INGREDIENT','INGREDIENT_TYPE','INGREDIENTS','2','1750',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1900','CRAFTED_INGREDIENT','INGREDIENT_TYPE','INGREDIENTS','3','1750',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1801','OTHER','OTHER_INGREDIENT_TYPE','OTHER_INGREDIENTS','1','1800',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1802','INGREDIENT_ORDER','OTHER_INGREDIENT_TYPE','OTHER_INGREDIENTS','2','1800',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1860','OTHER','RAW_INGREDIENT_TYPE','RAW_INGREDIENTS','1','1850',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1870','CHAIN','RAW_INGREDIENT_TYPE','RAW_INGREDIENTS','2','1850',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1880','LACE','RAW_INGREDIENT_TYPE','RAW_INGREDIENTS','3','1850',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1890','WIRE','RAW_INGREDIENT_TYPE','RAW_INGREDIENTS','4','1850',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1871','CHAIN_SNAKE','CHAIN_TYPE','CHAINS','1','1870',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1872','CHAIN_ROLO','CHAIN_TYPE','CHAINS','2','1870',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1881','LACE_FLAT','LACE_TYPE','LACE','1','1880',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1882','LACE_ROUND','LACE_TYPE','LACE','2','1880',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1891','WIRE_ROUND','WIRE_TYPE','WIRES','1','1890',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1892','WIRE_RECTANGULAR','WIRE_TYPE','WIRES','2','1890',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1893','WIRE_SQUARE','WIRE_TYPE','WIRES','3','1890',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1894','WIRE_TWISTED','WIRE_TYPE','WIRES','4','1890',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1895','WIRE_HALFROUND','WIRE_TYPE','WIRES','5','1890',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1896','WIRE_ROUND_HAMMERED','WIRE_TYPE','WIRES','6','1890',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1920','RING','CRAFTED_INGREDIENT_TYPE','CRAFTED_INGREDIENTS','2','1900',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1930','SCALE','CRAFTED_INGREDIENT_TYPE','CRAFTED_INGREDIENTS','3','1900',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1940','CLASP','CRAFTED_INGREDIENT_TYPE','CRAFTED_INGREDIENTS','4','1900',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1950','ATTACHMENT','CRAFTED_INGREDIENT_TYPE','CRAFTED_INGREDIENTS','5','1900',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1960','BEAD','CRAFTED_INGREDIENT_TYPE','CRAFTED_INGREDIENTS','6','1900',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'ANONYMOUS',to_date('13.01.19','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1921','JUMPRING_ROUND','RING_TYPE','RINGS','1','1920',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1922','JUMPRING_HALFROUND','RING_TYPE','RINGS','2','1920',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1931','SCALE_LARGE','SCALE_TYPE','SCALES','1','1930',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1932','SCALE_SMALL','SCALE_TYPE','SCALES','2','1930',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('121','SCALE_TINY','SCALE_TYPE','SCALES','3','1930',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1941','CLASP_GENERIC','CLASP_TYPE','CLASPS','1','1940',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1942','LOCK_LOBSTER','CLASP_TYPE','CLASPS','2','1940',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1943','LOCK_CARABINER','CLASP_TYPE','CLASPS','3','1940',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1944','LOCK_MAGNETIC_SLIDE','CLASP_TYPE','CLASPS','4','1940',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('122','KEYRING_SINGLE','ATTACHMENT_TYPE','ATTACHMENTS','1','1950',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1952','KEYRING_SINGLE_FLAT','ATTACHMENT_TYPE','ATTACHMENTS','2','1950',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1953','CLIP_GENERIC','ATTACHMENT_TYPE','ATTACHMENTS','3','1950',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1954','HAIRCLIP_SMALL','ATTACHMENT_TYPE','ATTACHMENTS','4','1950',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1955','EARRING_PAIR','ATTACHMENT_TYPE','ATTACHMENTS','5','1950',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1956','EARRING_WIRE_PAIR','ATTACHMENT_TYPE','ATTACHMENTS','6','1950',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1957','EARRING_CLASP_PAIR','ATTACHMENT_TYPE','ATTACHMENTS','7','1950',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1958','BROOCH_SMALL','ATTACHMENT_TYPE','ATTACHMENTS','8','1950',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1959','BEADING_PIN_VERTICAL_ROUND','ATTACHMENT_TYPE','ATTACHMENTS','9','1950',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1961','BEAD_ROUND','BEAD_TYPE','BEADS','1','1960',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('1962','BEAD_SQUARE','BEAD_TYPE','BEADS','2','1960',null,'LIST_OF_VALUES','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
Insert into MWD.DOMAINS (DOMAIN_VALUE_ID,DOMAIN_VALUE,DOMAIN_NAME,DOMAIN_REFLOC,SORT_ORDER,PARENT_DOMAIN_VALUE_ID,DESCRIPTION,DOMAIN_TYPE,ACTIVE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) values ('200','PERSON','DEFAULT','DOMAINS','1',null,null,'CONSTANT','Y','MWD',to_date('05.12.18','DD.MM.RR'),'MWD',to_date('05.12.18','DD.MM.RR'));
--------------------------------------------------------
--  DDL for Index DOMAINS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MWD"."DOMAINS_PK" ON "MWD"."DOMAINS" ("DOMAIN_VALUE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Index DOMAINS_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MWD"."DOMAINS_UK" ON "MWD"."DOMAINS" ("DOMAIN_NAME", "DOMAIN_VALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP" ;
--------------------------------------------------------
--  DDL for Trigger DOMAINS_BRIU
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MWD"."DOMAINS_BRIU" 
    BEFORE INSERT OR UPDATE ON MWD.DOMAINS 
    FOR EACH ROW 
DECLARE 
  domn_value_id number; 
  name_count number;
  value_in_list number;
BEGIN 
  if inserting then   
    if :new.domain_value_id is null then 
      select domn_seq.nextval 
        into domn_value_id 
        from dual; 
      :new.domain_value_id := domn_value_id; 
    end if; 

	if :new.sort_order is null then
		select nvl(max(domain_value_id),0)
			into name_count
			from domains
			where domain_name = :new.domain_name;		
		:new.sort_order := name_count + 1;
	end if;

	-- in lieu of check constraint.
	if :new.domain_type is not null then
		select nvl(count(*),0)
			into value_in_list
			from domains
			where domain_name = 'DOMAIN_TYPE'
			and domain_value = :new.domain_type;
		if (value_in_list = 0) then -- treat as if null to assign default.
			:new.domain_type := null;
		end if;
	end if;

	:new.user_created := user;
    :new.date_created := SYSDATE;
    :new.user_modified := user;
    :new.date_modified := SYSDATE;
  elsif updating THEN
    :new.user_modified := user;
    :new.date_modified := SYSDATE;
  end if;

END; 

/
ALTER TRIGGER "MWD"."DOMAINS_BRIU" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOMAINS_JNTRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MWD"."DOMAINS_JNTRG" 
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON MWD.DOMAINS for each row 
 Declare 
  rec MWD.DOMAINS_JN%ROWTYPE; 
  blank MWD.DOMAINS_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.DOMAIN_VALUE_ID := :NEW.DOMAIN_VALUE_ID; 
      rec.DOMAIN_VALUE := :NEW.DOMAIN_VALUE; 
      rec.DOMAIN_NAME := :NEW.DOMAIN_NAME; 
      rec.DOMAIN_REFLOC := :NEW.DOMAIN_REFLOC; 
      rec.SORT_ORDER := :NEW.SORT_ORDER; 
      rec.PARENT_DOMAIN_VALUE_ID := :NEW.PARENT_DOMAIN_VALUE_ID; 
      rec.DESCRIPTION := :NEW.DESCRIPTION; 
      rec.DOMAIN_TYPE := :NEW.DOMAIN_TYPE; 
      rec.ACTIVE := :NEW.ACTIVE; 
      rec.USER_CREATED := :NEW.USER_CREATED; 
      rec.DATE_CREATED := :NEW.DATE_CREATED; 
      rec.USER_MODIFIED := :NEW.USER_MODIFIED; 
      rec.DATE_MODIFIED := :NEW.DATE_MODIFIED; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.DOMAIN_VALUE_ID := :OLD.DOMAIN_VALUE_ID; 
      rec.DOMAIN_VALUE := :OLD.DOMAIN_VALUE; 
      rec.DOMAIN_NAME := :OLD.DOMAIN_NAME; 
      rec.DOMAIN_REFLOC := :OLD.DOMAIN_REFLOC; 
      rec.SORT_ORDER := :OLD.SORT_ORDER; 
      rec.PARENT_DOMAIN_VALUE_ID := :OLD.PARENT_DOMAIN_VALUE_ID; 
      rec.DESCRIPTION := :OLD.DESCRIPTION; 
      rec.DOMAIN_TYPE := :OLD.DOMAIN_TYPE; 
      rec.ACTIVE := :OLD.ACTIVE; 
      rec.USER_CREATED := :OLD.USER_CREATED; 
      rec.DATE_CREATED := :OLD.DATE_CREATED; 
      rec.USER_MODIFIED := :OLD.USER_MODIFIED; 
      rec.DATE_MODIFIED := :OLD.DATE_MODIFIED; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into MWD.DOMAINS_JN VALUES rec; 
  END; 

/
ALTER TRIGGER "MWD"."DOMAINS_JNTRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table DOMAINS
--------------------------------------------------------

  ALTER TABLE "MWD"."DOMAINS" ADD CONSTRAINT "DOMAINS_UK" UNIQUE ("DOMAIN_NAME", "DOMAIN_VALUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP"  ENABLE;
  ALTER TABLE "MWD"."DOMAINS" ADD CONSTRAINT "DOMAINS_PK" PRIMARY KEY ("DOMAIN_VALUE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BP"  ENABLE;
  ALTER TABLE "MWD"."DOMAINS" MODIFY ("DATE_MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "MWD"."DOMAINS" MODIFY ("USER_MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "MWD"."DOMAINS" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "MWD"."DOMAINS" MODIFY ("USER_CREATED" NOT NULL ENABLE);
  ALTER TABLE "MWD"."DOMAINS" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "MWD"."DOMAINS" MODIFY ("DOMAIN_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MWD"."DOMAINS" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "MWD"."DOMAINS" MODIFY ("DOMAIN_REFLOC" NOT NULL ENABLE);
  ALTER TABLE "MWD"."DOMAINS" MODIFY ("DOMAIN_NAME" NOT NULL ENABLE);
  ALTER TABLE "MWD"."DOMAINS" MODIFY ("DOMAIN_VALUE" NOT NULL ENABLE);
  ALTER TABLE "MWD"."DOMAINS" MODIFY ("DOMAIN_VALUE_ID" NOT NULL ENABLE);
