REM   Script: MWD Schema
REM   STAGE 1: DML FOR DOMAINS


-- ALL FROM EXCEL: DATA_DML_DOMAINS- DD 06/10/2018 13:00. upd values 02/12/2018.
-- ALL FROM EXCEL: DATA_DML_DOMAINS- DD 25/09/2018 13:00. UPD VALUES 02/12/2018.

-----

ALTER TABLE MWD.DOMAINS
    DISABLE ALL TRIGGERS;

-- INSERT THESE WITH TRIGGER DISABLED ONLY.
insert into MWD.DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) 
	VALUES  (1,'DOMAIN','TYPE','DOMAINS',1,NULL,'LIST_OF_VALUES',USER, SYSDATE, USER, SYSDATE); -- HARDCODED ID, ALLOWED.
insert into MWD.DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'DOMAIN' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES','DOMAIN_TYPE','DOMAINS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'DOMAIN' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES',USER, SYSDATE, USER, SYSDATE); -- HARDCODED ID, ALLOWED.
insert into MWD.DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'DOMAIN' AND DOMAIN_NAME = 'TYPE'),'CONSTANT','DOMAIN_TYPE','DOMAINS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'DOMAIN' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES',USER, SYSDATE, USER, SYSDATE); -- HARDCODED ID, ALLOWED.

-----

ALTER TABLE MWD.DOMAINS
    ENABLE ALL TRIGGERS;

-----

insert into MWD.DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (10,'DOMAIN','ACTIVE','MWD_DOMAINS',1,NULL,'LIST_OF_VALUES'); -- HARDCODED ID, ALLOWED.
insert into MWD.DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM MWD.DOMAINS WHERE DOMAIN_VALUE = 'DOMAIN' AND DOMAIN_NAME = 'ACTIVE'),'y','DOMAIN_ACTIVE','DOMAINS',1,(SELECT DOMAIN_VALUE_ID FROM MWD.DOMAINS WHERE DOMAIN_VALUE = 'DOMAIN' AND DOMAIN_NAME = 'ACTIVE'),'LIST_OF_VALUES');
insert into MWD.DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM MWD.DOMAINS WHERE DOMAIN_VALUE = 'DOMAIN' AND DOMAIN_NAME = 'ACTIVE'),'N','DOMAIN_ACTIVE','DOMAINS',2,(SELECT DOMAIN_VALUE_ID FROM MWD.DOMAINS WHERE DOMAIN_VALUE = 'DOMAIN' AND DOMAIN_NAME = 'ACTIVE'),'LIST_OF_VALUES');

-----

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (50,'ITEM','AVAILABILITY','DOMAINS',1,NULL,'LIST_OF_VALUES'); -- HARDCODED ID, ALLOWED.
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'AVAILABILITY'),'IN_STOCK','ITEM_AVAILABILITY','ITEMS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'AVAILABILITY'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'AVAILABILITY'),'OUT_OF_STOCK','ITEM_AVAILABILITY','ITEMS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'AVAILABILITY'),'LIST_OF_VALUES');
	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (100,'ITEM','SALE_STATUS','DOMAINS',1,NULL,'LIST_OF_VALUES'); -- HARDCODED ID, ALLOWED.
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'SALE_STATUS'),'NONE','ITEM_SALE_STATUS','ITEM_DETAILS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'SALE_STATUS'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'SALE_STATUS'),'FOR_SALE','ITEM_SALE_STATUS','ITEM_DETAILS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'SALE_STATUS'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'SALE_STATUS'),'SOLD','ITEM_SALE_STATUS','ITEM_DETAILS',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'SALE_STATUS'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (4+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NONE' AND DOMAIN_NAME = 'ITEM_SALE_STATUS'),'BACKORDER','ITEM_SALE_STATUS','ITEM_DETAILS',4,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'SALE_STATUS'),'LIST_OF_VALUES');
		
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (150,'WEAVE','COMPLEXITY','DOMAINS',1,NULL,'LIST_OF_VALUES'); -- HARDCODED ID, ALLOWED.
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WEAVE' AND DOMAIN_NAME = 'COMPLEXITY'),'BEGINNER','WEAVE_COMPLEXITY','WEAVES',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WEAVE' AND DOMAIN_NAME = 'COMPLEXITY'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WEAVE' AND DOMAIN_NAME = 'COMPLEXITY'),'INTERMEDIATE','WEAVE_COMPLEXITY','WEAVES',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WEAVE' AND DOMAIN_NAME = 'COMPLEXITY'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WEAVE' AND DOMAIN_NAME = 'COMPLEXITY'),'EXPERT','WEAVE_COMPLEXITY','WEAVES',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WEAVE' AND DOMAIN_NAME = 'COMPLEXITY'),'LIST_OF_VALUES');

	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (200,'PERSON','DEFAULT','DOMAINS',1,NULL,'CONSTANT'); -- HARDCODED ID, ALLOWED.

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (250,'ADDRESS','TYPE','DOMAINS',2,NULL,'LIST_OF_VALUES'); -- HARDCODED ID, ALLOWED.
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ADDRESS' AND DOMAIN_NAME = 'TYPE'),'STORAGE','ADDRESS_TYPE','LOCATION_ADDRESSES',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ADDRESS' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ADDRESS' AND DOMAIN_NAME = 'TYPE'),'ESTABLISHMENT','ADDRESS_TYPE','LOCATION_ADDRESSES',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ADDRESS' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ADDRESS' AND DOMAIN_NAME = 'TYPE'),'ONLINE','ADDRESS_TYPE','LOCATION_ADDRESSES',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ADDRESS' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES');
INSERT INTO MWD.DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE, ACTIVE) 
	VALUES (4+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ADDRESS' AND DOMAIN_NAME = 'TYPE'), 'HOME', 'ADDRESS_TYPE', 'LOCATION_ADDRESSES',4,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ADDRESS' AND DOMAIN_NAME = 'TYPE'), 'LIST_OF_VALUES');
INSERT INTO MWD.DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE, ACTIVE) 
	VALUES (5+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ADDRESS' AND DOMAIN_NAME = 'TYPE'), 'OTHER', 'ADDRESS_TYPE', 'LOCATION_ADDRESSES',5,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ADDRESS' AND DOMAIN_NAME = 'TYPE'), 'LIST_OF_VALUES');

*/
    

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (300,'ORDER','TYPE','DOMAINS',3,NULL,'LIST_OF_VALUES'); -- HARDCODED ID, ALLOWED.
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER' AND DOMAIN_NAME = 'TYPE'),'PURCHASE','ORDER_TYPE','ORDERS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER' AND DOMAIN_NAME = 'TYPE'),'SALE','ORDER_TYPE','ORDERS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES');
	
    
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (350,'ORDER','STATUS','DOMAINS',1,NULL,'LIST_OF_VALUES'); -- HARDCODED ID, ALLOWED.
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER' AND DOMAIN_NAME = 'STATUS'),'ORDERED','ORDER_STATUS','ORDERS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER' AND DOMAIN_NAME = 'STATUS'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER' AND DOMAIN_NAME = 'STATUS'),'PAID','ORDER_STATUS','ORDERS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER' AND DOMAIN_NAME = 'STATUS'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER' AND DOMAIN_NAME = 'STATUS'),'CANCELLED','ORDER_STATUS','ORDERS',4,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER' AND DOMAIN_NAME = 'STATUS'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (4+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER' AND DOMAIN_NAME = 'STATUS'),'COMPLETED','ORDER_STATUS','ORDERS',5,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER' AND DOMAIN_NAME = 'STATUS'),'LIST_OF_VALUES');
	

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (400,'ORDER_ITEM','STATUS','DOMAINS',2,NULL,'LIST_OF_VALUES'); -- HARDCODED ID, ALLOWED.
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER_ITEM' AND DOMAIN_NAME = 'STATUS'),'TO_DELIVER','ITEM_STATUS','ORDER_ITEMS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER_ITEM' AND DOMAIN_NAME = 'STATUS'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER_ITEM' AND DOMAIN_NAME = 'STATUS'),'DELIVERED','ITEM_STATUS','ORDER_ITEMS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER_ITEM' AND DOMAIN_NAME = 'STATUS'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER_ITEM' AND DOMAIN_NAME = 'STATUS'),'CANCELLED','ITEM_STATUS','ORDER_ITEMS',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORDER_ITEM' AND DOMAIN_NAME = 'STATUS'),'LIST_OF_VALUES');


---- ITEMS ----

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1000,'ITEM','TYPE','DOMAINS',4,NULL,'LIST_OF_VALUES'); -- HARDCODED ID, ALLOWED.

---- ITEMS MASTERLIST ----

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (100+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'TYPE'),'OTHER','ITEM_TYPE','ITEMS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES'); 
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (200+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'TYPE'),'KIT','ITEM_TYPE','ITEMS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES');	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (300+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'TYPE'),'SET','ITEM_TYPE','ITEMS',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES');	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (400+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'TYPE'),'TOOL','ITEM_TYPE','ITEMS',4,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (500+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'TYPE'),'CREATED_ITEM','ITEM_TYPE','ITEMS',5,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (750+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'TYPE'),'INGREDIENT','ITEM_TYPE','ITEMS',6,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ITEM' AND DOMAIN_NAME = 'TYPE'),'LIST_OF_VALUES');

---- OTHER_ITEM SUBLIST ----

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (10+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_TYPE'),'OTHER','OTHER_ITEM_TYPE','OTHER_ITEMS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (20+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_TYPE'),'ITEM_ORDER','OTHER_ITEM_TYPE','OTHER_ITEMS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');

---- KIT SUBLIST ----
	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (10+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'KIT' AND DOMAIN_NAME = 'ITEM_TYPE'),'KIT_ORDER','KIT_TYPE','KITS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'KIT' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (20+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'KIT' AND DOMAIN_NAME = 'ITEM_TYPE'),'KIT_MAKE','KIT_TYPE','KITS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'KIT' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
	
---- SET SUBLIST ----
	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (10+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SET' AND DOMAIN_NAME = 'ITEM_TYPE'),'SET_ORDER','SET_TYPE','SETS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SET' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (20+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SET' AND DOMAIN_NAME = 'ITEM_TYPE'),'SET_MAKE','SET_TYPE','SETS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SET' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');

---- TOOLS SUBLIST ----

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (10+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'TOOL' AND DOMAIN_NAME = 'ITEM_TYPE'),'OTHER','TOOL_TYPE','TOOLS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'TOOL' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');		
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (20+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'TOOL' AND DOMAIN_NAME = 'ITEM_TYPE'),'PLIERS','TOOL_TYPE','TOOLS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'TOOL' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (30+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'TOOL' AND DOMAIN_NAME = 'ITEM_TYPE'),'CALIPER','TOOL_TYPE','TOOLS',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'TOOL' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (40+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'TOOL' AND DOMAIN_NAME = 'ITEM_TYPE'),'BOX','TOOL_TYPE','TOOLS',4,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'TOOL' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (50+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'TOOL' AND DOMAIN_NAME = 'ITEM_TYPE'),'MAGNIFYING_GLASS','TOOL_TYPE','TOOLS',5,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'TOOL' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (60+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'TOOL' AND DOMAIN_NAME = 'ITEM_TYPE'),'RUBBER_COATING','TOOL_TYPE','TOOLS',6,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'TOOL' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
	
---- CREATED ITEMS SUBLIST ----

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (25+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CREATED_ITEM' AND DOMAIN_NAME = 'ITEM_TYPE'),'OTHER','CREATED_ITEM_TYPE','CREATED_ITEMS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CREATED_ITEM' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (50+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CREATED_ITEM' AND DOMAIN_NAME = 'ITEM_TYPE'),'JEWELRY','CREATED_ITEM_TYPE','CREATED_ITEMS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CREATED_ITEM' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (75+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CREATED_ITEM' AND DOMAIN_NAME = 'ITEM_TYPE'),'ACCESSORY','CREATED_ITEM_TYPE','CREATED_ITEMS',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CREATED_ITEM' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (100+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CREATED_ITEM' AND DOMAIN_NAME = 'ITEM_TYPE'),'ORNAMENT','CREATED_ITEM_TYPE','CREATED_ITEMS',4,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CREATED_ITEM' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'JEWELRY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'OTHER','JEWELRY_TYPE','JEWELRY',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE =  'JEWELRY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'JEWELRY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'BRACELET','JEWELRY_TYPE','JEWELRY',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE =  'JEWELRY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'JEWELRY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'NECKLACE','JEWELRY_TYPE','JEWELRY',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'JEWELRY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (4+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'JEWELRY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'PENDANT','JEWELRY_TYPE','JEWELRY',4,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'JEWELRY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (5+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'JEWELRY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'CHOKER','JEWELRY_TYPE','JEWELRY',5,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'JEWELRY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (6+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'JEWELRY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'EARRINGS','JEWELRY_TYPE','JEWELRY',6,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'JEWELRY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'LIST_OF_VALUES');
	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ACCESSORY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'OTHER','ACCESSORY_TYPE','ACCESSORIES',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ACCESSORY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ACCESSORY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'KEYCHAIN','ACCESSORY_TYPE','ACCESSORIES',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ACCESSORY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ACCESSORY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'HAIRCLIP','ACCESSORY_TYPE','ACCESSORIES',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ACCESSORY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (4+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ACCESSORY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'BROOCH','ACCESSORY_TYPE','ACCESSORIES',4,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ACCESSORY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (5+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ACCESSORY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'BOOKMARK','ACCESSORY_TYPE','ACCESSORIES',5,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ACCESSORY' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'LIST_OF_VALUES');
	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORNAMENT' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'OTHER','ORNAMENT_TYPE','ORNAMENTS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORNAMENT' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORNAMENT' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'CHRISTMAS_TREE_HANGER','ORNAMENT_TYPE','ORNAMENTS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ORNAMENT' AND DOMAIN_NAME = 'CREATED_ITEM_TYPE'),'LIST_OF_VALUES');
	
--- INGREDIENT SUBLIST ----

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (50+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'INGREDIENT' AND DOMAIN_NAME = 'ITEM_TYPE'),'OTHER','INGREDIENT_TYPE','INGREDIENTS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'INGREDIENT' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (100+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'INGREDIENT' AND DOMAIN_NAME = 'ITEM_TYPE'),'RAW_INGREDIENT','INGREDIENT_TYPE','INGREDIENTS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'INGREDIENT' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (150+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'INGREDIENT' AND DOMAIN_NAME = 'ITEM_TYPE'),'CRAFTED_INGREDIENT','INGREDIENT_TYPE','INGREDIENTS',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'INGREDIENT' AND DOMAIN_NAME = 'ITEM_TYPE'),'LIST_OF_VALUES');

---- INGREDIENT => OTHER INGREDIENT SUBLIST ----
	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'OTHER','OTHER_INGREDIENT_TYPE','OTHER_INGREDIENTS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'INGREDIENT_ORDER','OTHER_INGREDIENT_TYPE','OTHER_INGREDIENTS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'LIST_OF_VALUES');
	
---- INGREDIENT => RAW INGREDIENT SUBLIST ----

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (10+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RAW_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'OTHER','RAW_INGREDIENT_TYPE','RAW_INGREDIENTS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RAW_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (20+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RAW_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'CHAIN','RAW_INGREDIENT_TYPE','RAW_INGREDIENTS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RAW_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (30+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RAW_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'LACE','RAW_INGREDIENT_TYPE','RAW_INGREDIENTS',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RAW_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (40+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RAW_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'WIRE','RAW_INGREDIENT_TYPE','RAW_INGREDIENTS',4,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RAW_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'LIST_OF_VALUES');	
	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CHAIN' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'CHAIN_SNAKE','CHAIN_TYPE','CHAINS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CHAIN' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CHAIN' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'CHAIN_ROLO','CHAIN_TYPE','CHAINS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CHAIN' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'LIST_OF_VALUES');
	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'LACE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'LACE_FLAT','LACE_TYPE','LACE',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'LACE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'LACE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'LACE_ROUND','LACE_TYPE','LACE',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'LACE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'LIST_OF_VALUES');
	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WIRE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'WIRE_ROUND','WIRE_TYPE','WIRES',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WIRE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WIRE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'WIRE_RECTANGULAR','WIRE_TYPE','WIRES',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WIRE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WIRE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'WIRE_SQUARE','WIRE_TYPE','WIRES',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WIRE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (4+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WIRE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'WIRE_TWISTED','WIRE_TYPE','WIRES',4,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WIRE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (5+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WIRE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'WIRE_HALFROUND','WIRE_TYPE','WIRES',5,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WIRE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (6+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WIRE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'WIRE_ROUND_HAMMERED','WIRE_TYPE','WIRES',6,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'WIRE' AND DOMAIN_NAME = 'RAW_INGREDIENT_TYPE'),'LIST_OF_VALUES');
	
---- INGREDIENT => CRAFTED INGREDIENT SUBLIST ----
	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (20+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CRAFTED_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'RING','CRAFTED_INGREDIENT_TYPE','CRAFTED_INGREDIENTS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CRAFTED_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (30+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CRAFTED_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'SCALE','CRAFTED_INGREDIENT_TYPE','CRAFTED_INGREDIENTS',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CRAFTED_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (40+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CRAFTED_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'CLASP','CRAFTED_INGREDIENT_TYPE','CRAFTED_INGREDIENTS',4,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CRAFTED_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (50+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CRAFTED_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'ATTACHMENT','CRAFTED_INGREDIENT_TYPE','CRAFTED_INGREDIENTS',5,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CRAFTED_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (60+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CRAFTED_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'BEAD','CRAFTED_INGREDIENT_TYPE','CRAFTED_INGREDIENTS',55+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CRAFTED_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CRAFTED_INGREDIENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'LIST_OF_VALUES');
	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RING' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'JUMPRING_ROUND','RING_TYPE','RINGS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RING' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RING' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'JUMPRING_HALFROUND','RING_TYPE','RINGS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RING' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SCALE' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'SCALE_LARGE','SCALE_TYPE','SCALES',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SCALE' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SCALE' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'SCALE_SMALL','SCALE_TYPE','SCALES',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SCALE' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SCALE' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'SCALE_TINY','SCALE_TYPE','SCALES',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SCALE' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CLASP' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'CLASP_GENERIC','CLASP_TYPE','CLASPS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CLASP' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CLASP' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LOCK_LOBSTER','CLASP_TYPE','CLASPS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CLASP' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CLASP' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LOCK_CARABINER','CLASP_TYPE','CLASPS',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CLASP' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (4+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CLASP' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LOCK_MAGNETIC_SLIDE','CLASP_TYPE','CLASPS',4,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'CLASP' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');

insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'INGREDIENT_TYPE'),'KEYRING_SINGLE','ATTACHMENT_TYPE','ATTACHMENTS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'KEYRING_SINGLE_FLAT','ATTACHMENT_TYPE','ATTACHMENTS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'CLIP_GENERIC','ATTACHMENT_TYPE','ATTACHMENTS',3,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (4+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'HAIRCLIP_SMALL','ATTACHMENT_TYPE','ATTACHMENTS',4,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (5+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'EARRING_PAIR','ATTACHMENT_TYPE','ATTACHMENTS',5,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (6+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'EARRING_WIRE_PAIR','ATTACHMENT_TYPE','ATTACHMENTS',6,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (7+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'EARRING_CLASP_PAIR','ATTACHMENT_TYPE','ATTACHMENTS',7,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (8+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'BROOCH_SMALL','ATTACHMENT_TYPE','ATTACHMENTS',8,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (9+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'BEADING_PIN_VERTICAL_ROUND','ATTACHMENT_TYPE','ATTACHMENTS',9,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ATTACHMENT' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'BEAD' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'BEAD_ROUND','BEAD_TYPE','BEADS',1,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'BEAD' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'BEAD' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'BEAD_SQUARE','BEAD_TYPE','BEADS',2,(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'BEAD' AND DOMAIN_NAME = 'CRAFTED_INGREDIENT_TYPE'),'LIST_OF_VALUES');
	
---- no longer needed 02/12/2018, COMMENT OUT.	
/* 	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (200,'OTHER','ITEM_MATERIAL','INGREDIENTS',200,NULL,'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'OTHER_METAL','ITEM_MATERIAL','INGREDIENTS',1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (10+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'STAINLESS_STEEL','ITEM_MATERIAL','INGREDIENTS',10+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'STAINLESS_STEEL' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'BLACKENED_STAINLESS_STEEL','ITEM_MATERIAL','INGREDIENTS',1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'STAINLESS_STEEL' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'STAINLESS_STEEL' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'STAINLESS_STEEL' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'PLATED_STAINLESS_STEEL','ITEM_MATERIAL','INGREDIENTS',2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'STAINLESS_STEEL' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'STAINLESS_STEEL' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (20+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'BASE_ALUMINIUM','ITEM_MATERIAL','INGREDIENTS',20+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ALUMINIUM' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'ANODIZED_ALUMINIUM','ITEM_MATERIAL','INGREDIENTS',1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ALUMINIUM' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ALUMINIUM' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'ENAMELLED_ALUMINIUM','ITEM_MATERIAL','INGREDIENTS',2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'ALUMINIUM' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (30+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'BRONZE','ITEM_MATERIAL','INGREDIENTS',30+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (40+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'STEEL','ITEM_MATERIAL','INGREDIENTS',40+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (50+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'SILVER','ITEM_MATERIAL','INGREDIENTS',50+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SILVER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'STERLING_SILVER','ITEM_MATERIAL','INGREDIENTS',1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SILVER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SILVER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SILVER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'PURE_SILVER','ITEM_MATERIAL','INGREDIENTS',2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SILVER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'SILVER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (60+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'COPPER','ITEM_MATERIAL','INGREDIENTS',60+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'COPPER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'SILVER_FILLED_COPPER','ITEM_MATERIAL','INGREDIENTS',1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'COPPER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'COPPER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'COPPER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'SILVER_PLATED_COPPER','ITEM_MATERIAL','INGREDIENTS',2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'COPPER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'COPPER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'COPPER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'GOLD_PLATED_COPPER','ITEM_MATERIAL','INGREDIENTS',3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'COPPER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'COPPER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (100+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LEATHER','ITEM_MATERIAL','INGREDIENTS',100+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'LEATHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'SUEDE','ITEM_MATERIAL','INGREDIENTS',1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'LEATHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'LEATHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'LEATHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'FAUX_LEATHER','ITEM_MATERIAL','INGREDIENTS',2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'LEATHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'LEATHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'LEATHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'FAUX_SUEDE','ITEM_MATERIAL','INGREDIENTS',3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'LEATHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'LEATHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (110+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'STONE','ITEM_MATERIAL','INGREDIENTS',110+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'STONE' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'GEMSTONE','ITEM_MATERIAL','INGREDIENTS',1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'STONE' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'STONE' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'STONE' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'STONE_OTHER','ITEM_MATERIAL','INGREDIENTS',2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'STONE' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'STONE' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (120+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'WOOD','ITEM_MATERIAL','INGREDIENTS',120+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (130+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'GLASS','ITEM_MATERIAL','INGREDIENTS',130+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (140+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'RUBBER','ITEM_MATERIAL','INGREDIENTS',140+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'OTHER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RUBBER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'EPDM','ITEM_MATERIAL','INGREDIENTS',1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RUBBER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'RUBBER' AND DOMAIN_NAME = 'ITEM_MATERIAL'),'LIST_OF_VALUES');

	
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) VALUES 
	(450,'NATURAL','ITEM_COLOR','INGREDIENTS',1,NULL,'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'COLOR_MIX','ITEM_COLOR','INGREDIENTS',1+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'RAINBOW','ITEM_COLOR','INGREDIENTS',2+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'RED','ITEM_COLOR','INGREDIENTS',3+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (4+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'PURPLE','ITEM_COLOR','INGREDIENTS',4+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (5+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'GREEN','ITEM_COLOR','INGREDIENTS',5+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (6+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'ORANGE','ITEM_COLOR','INGREDIENTS',6+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES(7+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'PINK','ITEM_COLOR','INGREDIENTS',7+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (8+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'YELLOW','ITEM_COLOR','INGREDIENTS',8+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES (9+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'BLUE','ITEM_COLOR','INGREDIENTS',9+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (10+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'BLACKENED_STAINLESS_STEEL','ITEM_COLOR','INGREDIENTS',10+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (11+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'BROWN','ITEM_COLOR','INGREDIENTS',11+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (12+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'COFFEE_BROWN','ITEM_COLOR','INGREDIENTS',12+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (13+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'DEEP_RED','ITEM_COLOR','INGREDIENTS',13+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (14+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'BLACK_SILVER','ITEM_COLOR','INGREDIENTS',14+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (15+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'SILVER','ITEM_COLOR','INGREDIENTS',15+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (16+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'DARK_COFFEE_BROWN','ITEM_COLOR','INGREDIENTS',16+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (17+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'DARK_GREEN','ITEM_COLOR','INGREDIENTS',17+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (18+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'DARK_STEEL_BLUE','ITEM_COLOR','INGREDIENTS',18+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (19+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'PURPLE_RED','ITEM_COLOR','INGREDIENTS',19+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (20+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'TURQUOISE','ITEM_COLOR','INGREDIENTS',20+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (21+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'BEIGE','ITEM_COLOR','INGREDIENTS',21+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (22+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIGHT_BROWN','ITEM_COLOR','INGREDIENTS',22+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (23+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'SHINY_RED','ITEM_COLOR','INGREDIENTS',23+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (24+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'SHINY_STEEL','ITEM_COLOR','INGREDIENTS',24+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
insert into DOMAINS (DOMAIN_VALUE_ID, DOMAIN_VALUE, DOMAIN_NAME, DOMAIN_REFLOC, SORT_ORDER, PARENT_DOMAIN_VALUE_ID, DOMAIN_TYPE) 
	VALUES  (25+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'TRANSPARENT','ITEM_COLOR','INGREDIENTS',25+(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),(SELECT DOMAIN_VALUE_ID FROM DOMAINS WHERE DOMAIN_VALUE = 'NATURAL' AND DOMAIN_NAME = 'ITEM_COLOR'),'LIST_OF_VALUES');
 */
---------

commit;
/