REM   Script: MWD Schema
REM   STAGE 3: DML FOR TABLES: WEAVES, WEAVE ARS.


-- ALL FROM EXCEL: DATA_DML_weaves - DD 07/10/2018 21:30. upd column names / rows inserted on 02/12/2018.

INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (1,'Byzantine','Byzantine 2, Etruscan, Birdcage, Fool''s Dilemma, Idiot''s Trap, Idiot''s Delight, Bird''s Nest',NULL,'BEGINNER','Single units of Box Chain separated by sets of connector rings. Most commonly 2 connectors.','4 open rings to 2 closed rings. Make units of 2-in-2 and leave the last 2 open to connect units.','http://www.mailleartisans.org/weaves/weavedisplay.php?key=13');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (2,'Byzantine 1','Byzantine 2, Etruscan, Birdcage, Fool''s Dilemma, Idiot''s Trap, Idiot''s Delight, Bird''s Nest',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Byzantine'),'BEGINNER','Single units of Box Chain separated by 1 connector ring.','3 open rings to 2 closed rings. Make units of 2-in-2 and leave the last 1 open to connect units.','http://www.mailleartisans.org/weaves/weavedisplay.php?key=13');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (3,'Byzantine 3','Byzantine 2, Etruscan, Birdcage, Fool''s Dilemma, Idiot''s Trap, Idiot''s Delight, Bird''s Nest',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Byzantine'),'BEGINNER','Single units of Box Chain separated by sets of 3 connector rings.','5 open rings to 2 closed rings. Make units of 2-in-2 and leave the last 3 open to connect units.','http://www.mailleartisans.org/weaves/weavedisplay.php?key=13');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (4,'Byzantine 4','Byzantine 2, Etruscan, Birdcage, Fool''s Dilemma, Idiot''s Trap, Idiot''s Delight, Bird''s Nest',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Byzantine'),'BEGINNER','Single units of Box Chain separated by sets of 4 connector rings.','6 open rings to 2 closed rings. Make units of 2-in-2 and leave the last 4 open to connect units.','http://www.mailleartisans.org/weaves/weavedisplay.php?key=13');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (5,'2 in 1 Chain','1 on 1',NULL,'BEGINNER','2 in 1 is the foundation of every chainmail weave, with four principal layouts: Japanese, European, Spiral and Persian.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=54');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (6,'Spiral 2 in 1','',(SELECT WEAVE_ID FROM weaves WHERE NAME = '2 in 1 Chain'),'BEGINNER','Spiral 2 in 1 chains have been twisted to their limit, and held in place by some other mechanism. The characteristic feature of this family is that each subsequent ring connection has a greater angle than the one preceding it.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=54');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (7,'European 2 in 1','',(SELECT WEAVE_ID FROM weaves WHERE NAME = '2 in 1 Chain'),'BEGINNER','European utilizes a through-the-eye connection, placing the rings in rows that have a lean. The direction of these rows is often called the grain of the weave.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=54');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (8,'Japanese 2 in 1','',(SELECT WEAVE_ID FROM weaves WHERE NAME = '2 in 1 Chain'),'BEGINNER','Japanese typically has connections at right angles, with sheets formed through the use of only the horizontal links.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=54');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (9,'Persian 2 in 1','',(SELECT WEAVE_ID FROM weaves WHERE NAME = '2 in 1 Chain'),'BEGINNER','Persians true base is HP 3 in 1. This is the setup of around-the-eye connections that allows for the Persian family to begin. ','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=54');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (10,'tRNA Chain','Stabilized Spiral 2 in 1',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Spiral 2 in 1'),'INTERMEDIATE','Named after "transfer ribonucleic acid" for its shape. This a a 2 in 1 Chain twisted with stabilizer rings. Natural twist, will not lay flat at this AR. Larger AR rings can be used to make it lay flat. Holding it up always twists it.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=1416');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (11,'European 4 in 1','E4-1',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'European 2 in 1'),'BEGINNER','European 4 in 1 is one of the most popular chainmail weaves known to mankind. It is what a lot of armour from the European middle ages was made out of. It is very easy to learn and is a versatile fabric weave that can be used to make things like shirts, coifs, dicebags, and inlays.  The sample displayed uses stainless steel rings made from .063" (1.60mm / 16 SWG) wire wrapped on 5/16" (7.94mm) mandrel. With a measured ID of .346" (8.79mm) these rings bear an AR of 5.5.  An AR of 2.9 is the minimum for E4-1. An AR of 3.0 is ideal for structural applications such as basketry. Inlays can be done in any AR possible with this weave, but are best done in the three to four range so they look less open. As a fabric, the maille maker will have to find a ring size that provides the desired openness and flexibility of the weave. Shirts, coifs, and other clothing items are generally made in the four to six range. Welded/riveted rings allow for higher ARs while maintaining good strength.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=6');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (12,'European 6 in 1','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'European 4 in 1'),'BEGINNER','European 6 in 1 is one of the simplest sheet weave progressions of European 4 in 1. In it, each ring passes through six others, creating a denser fabric, depending on the ring aspect ratio used. The minimum for this weave is an AR of 4.3.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=7');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (13,'Rhinos Snorting Drano','RSD',NULL,'INTERMEDIATE','Persian/European hybrid. Best with rings of a small AR. Many possible variations. ','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=27');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (14,'Helm Chain','Parallel Chain',NULL,'INTERMEDIATE','Two examples of converting Helm chain into sheet are Conundrum and Wyrm Skin.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=464');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (15,'Half Persian 3 in 1','',NULL,'INTERMEDIATE','Half Persian 3 in 1 is exactly one half of Full Persian 6 in 1. Half Persian 3 in 1 can be a standalone chain weave, or expanded into a sheet weave as well. Ideal AR: 4.3. Recommended AR range: 3.9 - 4.8. ','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=52');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (16,'Half Persian 5 in 1','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Half Persian 3 in 1'),'INTERMEDIATE','Has many of the same properties as Half Persian 3 in 1, but is more dense and lays wider at the base.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=291');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (17,'Full Persian','Full Persian 6 in 1',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Half Persian 3 in 1'),'INTERMEDIATE','The minimum AR lies in the neighbourhood of AR of 4.8 The weave is stiff and unbendable at this point, and remains relatively inflexible until the low 5s. Amounts of flexibility ideal for general mailling purposes are achieved starting around an AR of 5.3, although the chain retains a certain amount of "stiffness" that keeps it from being completely collapsable up to around 6. It can still be formed into structural ring shapes when opposite ends of the chain are affixed to each other. Still useful far above an AR of 6.0, individual ring strength withstanding.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=44');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (18,'Inverted Round','',NULL,'BEGINNER','Inverted Round is a variant of Roundmaille with the grain at a 90 degree angle. Can have captive rings added to produce Captive Inverted Round. Can have reinforced rings added to produce Reinforced Inverted Round, or Bore Worm.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=110');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (19,'Japanese 12 in 2','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Japanese 6 in 1'),'BEGINNER','Take the Japanese 6 in 1 weave, and double it. The main advantage of this weave, if you use the correct ring sizes, is a major increase in stability of the weave. The rings do not slip over one another or flop over, therefore the pattern always shows to its best. Japanese 12 in 2 made in larger AR pairings (example: ARs 5.8,4.3) can be successfully stabilized through the use of captive rings.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=343');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (20,'Japanese 6 in 1','Asa No Ha Gusari, Oriental 6 in 1',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Japanese 2 in 1'),'BEGINNER','There are two types of rings in this weave: vertical ones, which each go through two, and horizontal ones, which each go through six. Providing the wire diameter is kept the same between the horizontal and vertical rings, the minimum AR for the smaller ring is 2.0.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=16');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (21,'Flower','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Mobius Ball'),'INTERMEDIATE','The Flower weave is constructed of 3-ring Mobius Balls connected in series by 1 or more connector rings.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=25');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (22,'Box Chain','Box',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'European 4 in 1'),'INTERMEDIATE','Box chain is a simple European 4 in 1 variant that is four rows wide, with the fourth row connecting back onto the first making it into a chain weave.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=12');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (23,'Elfweave','Elf Weave',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'European 4 in 1'),'EXPERT','A Basic European 4 in 1 variation which uses some persian style connections to create this great looking weave. Rings shown are 18 gauge 3/16"" ID.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=300');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (24,'Flowers in Cages','Rosette Link',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Byzantine'),'INTERMEDIATE','This is a variation on Birdcage/Byzantine/Birdsnest that uses 3 ring rosettes inside the cages. Flowers in Cages is a weave by Baealiel Dreamseeker.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=76');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (25,'Jens Pind Linkage','JPL, JPL3, Jens Pind Linkage 3, Spiral 4 in 1',NULL,'EXPERT','Jens Pind is a 4-1 spiral weave, with a tight enough AR that the spiral locks in place.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=335');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (26,'Jacob''s Ladder','Jacob''s Chain, Magician''s Ladder, Spiral 3 in 1',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'European 6 in 1'),'INTERMEDIATE','This is what happens when you mess up a Half Persian 3 in 1..it happens ;) It is constructed the same as European 6 in 1 but with only 2 rows. It can also be used as a magicians prop, and creates a very nifty effect.','Weave Euro 6 in 1 and take off the third row.','http://www.mailleartisans.org/weaves/weavedisplay.php?key=281');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (27,'Celtic Visions','',NULL,'INTERMEDIATE','Japanese in structure but looks more like Celtic knotwork. Minimum AR is the classic two ring size combo. The central small rings, however, can be reduced to an AR of 2.0 since they only pass through two other rings. Also, while listed ARs use same wire diameter for both the large and small ring, the weave is often made with a smaller wire diameter for the smaller ring, as demonstrated in the tutorials.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=244');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (28,'Fourever Chain','Fourever 4 Chain',NULL,'INTERMEDIATE','Its basic structure consists of tightly woven 4-ring Mobius Balls, that are connected in a 2 in 1 Chain manner to a chain. And it holds its delicate structure only, if woven near the low AR limit, that is at 2.6 for the single-ring variants, and at 4.1 for the kinged ones - else a chain similar to a modified 4-ring Flower chain results. High-AR limits are not yet fully explored, but I propose not going above 2.9 (respectively 4.5 for the kinged version). And naturally there are further design options by using different ARs for Mobis and connectors.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=1178');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (29,'Fourever 6 Chain','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Fourever Chain'),'INTERMEDIATE','Its basic structure consists of tightly woven 4-ring Mobius Balls, that are connected in a 2 in 1 Chain manner to a chain. And it holds its delicate structure only, if woven near the low AR limit, that is at 2.6 for the single-ring variants, and at 4.1 for the kinged ones - else a chain similar to a modified 4-ring Flower chain results. High-AR limits are not yet fully explored, but I propose not going above 2.9 (respectively 4.5 for the kinged version). And naturally there are further design options by using different ARs for Mobis and connectors.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=1178');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (30,'Kinged Fourever Chain','Forget-Me-Knot Chain',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Fourever Chain'),'INTERMEDIATE','4-mobius kinged up as Forget-me-knot chain.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=1178');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (31,'Roundmaille','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'European 4 in 1'),'INTERMEDIATE','This weave is six rows wide European 4 in 1 with the sixth row connecting to the first. Best made with relatively low aspect ratios. The minimum is an AR of 3.2, which makes the weave ideal for structural applications. Recommended range: 3.3 - 4.0.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=15');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (32,'Mobius Ball','Möbius Ball, Moebius Ball',NULL,'INTERMEDIATE','Mobius Ball is a very unique chainmail weave as it is made out of a number of rings which can vary according to the ring size, how tightly it is being made, and its intended application. Every ring in a Mobius Ball passes through every other ring. Tight Mobius Balls with higher ring numbers make great stress toys. In this application the Mobius Ball is patented (US Pat. 541-3519) and also trademarked by Mead Simon. ','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=23');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (33,'Half Persian 4 in 1','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Half Persian 3 in 1'),'INTERMEDIATE','','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=50');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (34,'Jens Pind Linkage 4','JPL4',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Jens Pind Linkage'),'EXPERT','','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=439');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (35,'Jens Pind Linkage 5','JPL5',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Jens Pind Linkage'),'EXPERT','','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=372');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (36,'5-Point Small Scale Flower','5-Pointed Overlapping Scale Flower',NULL,'INTERMEDIATE','Not a weave, but a tutorial with sizes.','','http://www.mailleartisans.org/articles/articledisplay.php?key=598');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (37,'Captive Inverted Roundmaille','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Inverted Round'),'INTERMEDIATE','Inverted round with captive rings inside the chain. Minimum ARs for number of captives per cell: 1: 4.7 / 2: 5.5 / 3: 6.4 / 4: 7.4 / 5: 8.3','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=68');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (38,'Elfsheet','Elf Sheet',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Elfweave'),'EXPERT','','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=1099');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (39,'Vipera Berus','Northern Viper',NULL,'EXPERT','Third bastard son of mixing European and Hoodoo. Make 1 in 1 chain, connect sides like in hoodoo or louhi. Easy to make after you get the idea.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=471');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (40,'Vipera Berus Kinged','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Vipera Berus'),'EXPERT','Doubled up Vipera Berus.','','https://www.youtube.com/watch?v=UuTyyumo2Hk');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (41,'Vipera Berus Sheet','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Vipera Berus'),'EXPERT','This is real Vipera Berus Sheet. It is Vipera Berus 4 in 1 in which each strip of rings is connected to each other with a Hoodoo-like zigzag pattern. ','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=473');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (42,'Vipera Berus 4 in 1','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Vipera Berus'),'EXPERT','This weave is same to Vipera Berus as Louhi is to Hoodoo. It is a strip of European 4 in 1 with Hoodoo-like connections on the sides. ','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=472');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (43,'Dragonscale (small)','Dragonscale',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Dragonscale'),'EXPERT','Assuming the same wire size is used for both ring types in the weave, the minimum for the small ring is around AR of 3.6. The large ring in this case must have an AR that is at least 2.0 higher than the small rings.
(small ring ID + 2*WD) / WD). Dragonscale is basically two European 4 in 1 weaves interwoven. Two ring sizes must be used to make this weave. Large rings only go through small rings. The smaller ring outer diameter must be at least slightly smaller than the larger ring inner diameter.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=11');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (44,'Dragonscale (large)','Dragonscale',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Dragonscale'),'EXPERT','Assuming the same wire size is used for both ring types in the weave, the minimum for the small ring is around AR of 3.6. The large ring in this case must have an AR that is at least 2.0 higher than the small rings.
(small ring ID + 2*WD) / WD). Dragonscale is basically two European 4 in 1 weaves interwoven. Two ring sizes must be used to make this weave. Large rings only go through small rings. The smaller ring outer diameter must be at least slightly smaller than the larger ring inner diameter.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=11');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (45,'Dragonscale','',NULL,'EXPERT','Assuming the same wire size is used for both ring types in the weave, the minimum for the small ring is around AR of 3.6. The large ring in this case must have an AR that is at least 2.0 higher than the small rings.
(small ring ID + 2*WD) / WD). Dragonscale is basically two European 4 in 1 weaves interwoven. Two ring sizes must be used to make this weave. Large rings only go through small rings. The smaller ring outer diameter must be at least slightly smaller than the larger ring inner diameter.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=11');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (46,'4 Winds','',NULL,'EXPERT','I am not usually one to design weaves with multiple ring sizes, but this weave just lends itself so well to it. Rather than one big ring, two rings can also be used to connect each cell. When this is done the faces of each cell alternate directions. AR for the 4 Winds cells is 3.09. For the large connector rings the AR is around 4.5. ','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=981');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (47,'Sweetpea','',NULL,'EXPERT','It is very like Medo-Persian and Fieldstone. Each unit is joined by one ring on each side instead of 1 into 2 like Medo-Persian. 4.2 ar is perfect.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=852');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (48,'Candy Cane Cord','Spirally Goodness, CCC, Alternating Candy Cane Cord, or (A)CCC',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Byzantine'),'EXPERT','6 in 1 weave. Candy Cane Cord came forward after some experimentation with Byzantine, and can also be started using Box Chain. Variants exist with Full Persian 6 in 1 segments, using this method as an in-between connector to reverse the grain in an elegant way. A similar effect is seen on box chain and byzantine. A spiral effect is accomplished by weaving a segment as usual, and then weaving a segment of box chain. By combining these two aspects in different ways / amounts a plethora of variants can be made. This weave is primarily a chain/rope type weave, but variants from roundweave starters and quadweave starters unround into a very ugly sheet.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=1025');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (49,'Infinity Rose Fidget','',NULL,'EXPERT','This is not a weave, but a tutorial.','','https://lisaellis.selz.com/');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (50,'Moorish Rose','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Mobius Ball'),'EXPERT','Moorish Rose is a 9 in 1 weave made with 6-link Mobius Balls. The Mobius Balls are joined with three-link Mobius Balls made from the links on the corners of the six. The flat sides of the six are also joined together 2 in 2-stlye. Works with 22g 0.025" 5/32", 18g 0.048" 5/16". [Edit: Moorish Rose is essentially a progression of Brejão Flowers.]','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=1078');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (51,'Alligator Back','Euro-Persian Hybrid',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'European 4 in 1'),'EXPERT','Alligator Back is Crocodile Back based on European 4 in 1 instead of European 6 in 1. Made the same way as Persian Dragonscale but with only one side stitched up. This sample was a little tight with an AR of 4.16 (wire 1.2mm 5mm ID) so I recommend a slightly larger AR. ','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=819');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (52,'GSG','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Half Persian 3 in 1'),'EXPERT','GSG, named for the Great Southern Gathering where the weave was perfected, is a weave created by buddha. GSG is a Half Persian 3 Sheet 6 in 1 chain, turned sideways, two columns wide strip. There exist also three or more column wide GSG variants, that share the main weaving direction of basic GSG.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=200');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (53,'Pencil Weave','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Spiral 2 in 1'),'EXPERT','This is essentially a spiral variant of Hilt Chain. Each of the rings which are parallel in the Hilt Chain instead connect in a spiral 2 in 1 Chain. The pattern can be continued to form a tube with a diameter determined by the ring size. It is also a progression of Half Persian 3 in 1 Full Spiral. Any AR over 5.2 works. Pic is 14 SWG aluminum 5/8"" ID, AR ~= 7.8. Eight 2-1 spirals make one solid tube at this size. Number of spirals per tube ~= AR. This is closely related to Round Counterspiral 5 but Pencil Weave features both around-the-eye and through-the-eye connections while Round Counterspiral uses only around-the-eye. ','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=1331');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (54,'Dragonback','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Half Persian 3 in 1'),'EXPERT','Dragonback is two strips of Half Persian 3 in 1 stitched up the center on both sides with European 4 in 1. Persian Dragonscale is a similar weave, but the way the European 4 in 1 is connected to the Half Persian 3 in 1 is different. This weave is different on the top and bottom. The rings used are 18awg (1.0mm)/5.0mm with an AR of 5.0.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=1224');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (55,'Voodoo','',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Half Persian 3 in 1'),'EXPERT','Somewhat hard to describe without going into detail. It is very stable and relatively flexible.','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=188');
INSERT INTO weaves (WEAVE_ID, NAME, SYNONYMS, PARENT_WEAVE_ID, COMPLEXITY, DESCRIPTION, SPEED_WEAVE, SOURCE_URL) VALUES (56,'Alligator Back (small)','Euro-Persian Hybrid',(SELECT WEAVE_ID FROM weaves WHERE NAME = 'European 4 in 1'),'EXPERT','Alligator Back is Crocodile Back based on European 4 in 1 instead of European 6 in 1. Made the same way as Persian Dragonscale but with only one side stitched up. This sample was a little tight with an AR of 4.16 (wire 1.2mm 5mm ID) so I recommend a slightly larger AR. ','','http://www.mailleartisans.org/weaves/weavedisplay.php?key=819');

-- ALL FROM EXCEL: DATA_DML_weave_ars - DD 07/10/2018 01:30.

INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (1,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Byzantine'),3.55,3.2,3.9,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (2,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Byzantine 1'),3.2,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (3,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Byzantine 3'),4.3,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (4,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Byzantine 4'),4.9,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (5,(SELECT WEAVE_ID FROM weaves WHERE NAME = '2 in 1 Chain'),2.1,2,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (6,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Spiral 2 in 1'),2.1,2,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (7,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'European 2 in 1'),2.1,2,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (8,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Japanese 2 in 1'),2.1,2,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (9,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Persian 2 in 1'),2.1,2,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (10,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'tRNA Chain'),2.2,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (11,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'tRNA Chain'),4.1,NULL,NULL,2);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (12,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'European 4 in 1'),3.5,2.83,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (13,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'European 6 in 1'),4.9,4.25,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (14,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Rhinos Snorting Drano'),3.3,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (15,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Helm Chain'),4,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (16,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Helm Chain'),6.2,NULL,NULL,2);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (17,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Half Persian 3 in 1'),4.3,3.9,5,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (18,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Half Persian 5 in 1'),7,5.7,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (19,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Full Persian'),5.5,4.8,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (20,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Inverted Round'),4.3,3.5,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (21,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Roundmaille'),3.5,3.2,4,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (22,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Japanese 12 in 2'),5.5,5.2,5.8,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (23,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Japanese 12 in 2'),2.8,2.6,4.3,2);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (24,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Japanese 6 in 1'),3.3,2.9,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (25,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Japanese 6 in 1'),2.1,2,NULL,2);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (26,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Flower'),3.9,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (27,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Mobius Ball'),9.9,2,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (28,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Box Chain'),5.1,3.8,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (29,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Elfweave'),4.2,3.7,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (30,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Flowers in Cages'),3.5,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (31,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Jens Pind Linkage'),2.9,2.7,3.2,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (32,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Jacob''s Ladder'),4,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (33,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Celtic Visions'),5.3,5.1,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (34,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Celtic Visions'),3.3,2,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (35,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Fourever Chain'),2.7,2.6,2.9,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (36,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Fourever 6 Chain'),3.83,3.6,4,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (37,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Kinged Fourever Chain'),4.3,4.1,4.5,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (38,(SELECT WEAVE_ID FROM weaves WHERE NAME = '5-Point Small Scale Flower'),6.25,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (39,(SELECT WEAVE_ID FROM weaves WHERE NAME = '5-Point Small Scale Flower'),4.18,NULL,NULL,2);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (40,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Half Persian 4 in 1'),5,4.4,5.4,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (41,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Jens Pind Linkage 4'),4,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (42,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Jens Pind Linkage 5'),4.9,4.6,5.3,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (43,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Elfsheet'),4.2,4,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (44,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Vipera Berus'),3.3,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (45,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Vipera Berus Kinged'),5.3,5.2,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (46,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Vipera Berus Sheet'),4,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (47,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Captive Inverted Roundmaille'),5.6,4.7,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (48,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Vipera Berus 4 in 1'),3.1,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (49,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Dragonscale'),6.1,5.7,6.5,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (50,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Dragonscale'),3.9,3.7,4.6,2);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (51,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Dragonscale (large)'),6.5,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (52,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Dragonscale (large)'),4.6,3.5,NULL,2);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (53,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Dragonscale (small)'),5.9,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (54,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Dragonscale (small)'),3.9,3.5,NULL,2);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (55,(SELECT WEAVE_ID FROM weaves WHERE NAME = '4 Winds'),4.5,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (56,(SELECT WEAVE_ID FROM weaves WHERE NAME = '4 Winds'),3.1,NULL,NULL,2);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (57,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Sweetpea'),4,3.8,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (58,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Candy Cane Cord'),4.7,4.1,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (59,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Moorish Rose'),7,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (60,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Alligator Back'),4,4.16,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (61,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'GSG'),5,4.6,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (62,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Pencil Weave'),7.8,5.2,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (63,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Dragonback'),5,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (64,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Voodoo'),5.5,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (65,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Voodoo'),3.3,NULL,NULL,2);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (66,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Alligator Back (small)'),4.8,4.6,5,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (67,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Infinity Rose Fidget'),5.2,NULL,NULL,1);
INSERT INTO weave_ars (WEAVE_AR_ID, WEAVE_ID, OPTIMAL_AR, MIN_AR, MAX_AR, AR_SORT_ORDER) VALUES  (68,(SELECT WEAVE_ID FROM weaves WHERE NAME = 'Infinity Rose Fidget'),6.5,NULL,NULL,1);

COMMIT;
/